import { ServiceData } from "./types"

export const communicationService: ServiceData = {
    id: "communication",
    icon: "Megaphone",
    title: "Communication",
    color: "#C4D82E",
    gradient: "from-[#C4D82E]/20 via-[#C4D82E]/10 to-transparent",
    tagline: "Stratégie de Communication",
    description: "Stratégie de communication conforme au Code de la Communication gabonais (Loi n°019/2016) et à la réglementation de la HAC (Loi n°014/2023), pour une image maîtrisée et une présence responsable.",
    keyBenefits: [
      { icon: "Megaphone", text: "Visibilité renforcée", detail: "Image institutionnelle forte" },
      { icon: "Shield", text: "Gestion de crise", detail: "Réactivité et maîtrise" },
      { icon: "Target", text: "Impact digital", detail: "Présence en ligne optimisée" }
    ],
    workflow: [
      { step: "1", title: "Audit", description: "Analyse de votre communication actuelle et de votre image de marque", icon: "Search" },
      { step: "2", title: "Stratégie", description: "Définition d'un plan de communication adapté à vos objectifs", icon: "Target" },
      { step: "3", title: "Déploiement", description: "Mise en œuvre des actions de communication sur tous les canaux", icon: "Megaphone" },
      { step: "4", title: "Mesure", description: "Suivi des retombées et ajustement de la stratégie", icon: "BarChart3" }
    ],
    services: [
      {
        icon: "Megaphone",
        name: "Services de Communication",
        slug: "services-communication",
        tagline: "Valorisez votre image",
        description: "Une offre complète de communication conforme au cadre réglementaire gabonais pour renforcer votre positionnement et votre notoriété en toute légalité.",
        details: [
          {
            title: "Communication institutionnelle",
            content: "La communication institutionnelle des entreprises au Gabon est encadrée par le Code de la Communication (Loi n°019/2016), qui définit les règles applicables à la diffusion de messages à caractère institutionnel et commercial. Ce texte impose des obligations de transparence, de véracité et de respect de l'ordre public dans toute communication émanant d'une personne morale. Par ailleurs, l'Acte Uniforme OHADA sur les sociétés commerciales et le groupement d'intérêt économique (AUSCGIE 2014) impose que la dénomination sociale figure sur tous les actes et documents destinés aux tiers, incluant les supports de communication, papiers à en-tête, factures, devis et correspondances officielles.\n\nLa protection de votre identité visuelle et de vos créations graphiques est garantie par l'Accord de Bangui révisé en 2020, administré par l'Organisation Africaine de la Propriété Intellectuelle (OAPI). Cet accord couvre le dépôt et la protection des marques, des dessins et modèles industriels, ainsi que des noms commerciaux dans l'ensemble des dix-sept États membres de l'OAPI. Toute entreprise opérant au Gabon a intérêt à protéger sa marque, son logo et ses éléments distinctifs par un dépôt auprès de l'OAPI pour prévenir la contrefaçon et l'usurpation d'identité.\n\nLa communication institutionnelle implique également le respect des obligations de publicité légale. L'AUSCGIE 2014 prévoit la publication au Journal Officiel de toute modification statutaire (changement de dénomination, de siège social, de dirigeants), et l'article 516 impose la tenue d'une assemblée générale annuelle dans les six mois suivant la clôture de l'exercice. Toute modification statutaire doit être suivie d'une rectification au Registre du Commerce et du Crédit Mobilier (RCCM) dans un délai de trente jours.\n\nOdillon vous accompagne dans la construction d'une communication institutionnelle cohérente et juridiquement conforme. Nous concevons votre charte graphique, vos supports de communication (plaquettes, rapports annuels, site web, signalétique), et veillons à la conformité de chaque élément avec les obligations légales. Nous assurons également les démarches de dépôt de marque auprès de l'OAPI et le suivi des publications légales obligatoires, pour une image d'entreprise à la fois professionnelle et parfaitement sécurisée sur le plan juridique.",
            impact: "Image crédible, protégée juridiquement et conforme aux obligations légales"
          },
          {
            title: "Communication digitale",
            content: "La communication digitale au Gabon est encadrée par plusieurs textes législatifs qui imposent aux entreprises un cadre strict en matière de présence en ligne. La Loi n°001/2011, modifiée par la Loi n°025/2023, établit le régime de protection des données à caractère personnel et soumet toute collecte, traitement ou stockage de données utilisateurs au contrôle de l'Autorité de Protection des Données à caractère Personnel et de la Vie Privée (APDPVP). Cette autorité veille au respect des droits des personnes concernées et dispose de pouvoirs d'investigation et de sanction en cas de manquement.\n\nLa Haute Autorité de la Communication (HAC), réorganisée par la Loi n°014/2023, étend ses compétences de régulation aux contenus numériques. Elle dispose de pouvoirs de sanction graduels allant de l'avertissement à la suspension, voire au retrait de licence pour les médias en ligne. En 2024, la HAC a recensé 169 médias en ligne au Gabon, dont seulement 29 en règle avec la réglementation en vigueur. Cette réalité impose aux entreprises une vigilance accrue dans le choix de leurs partenaires médias numériques et dans la gestion de leur propre présence en ligne.\n\nConcrètement, toute entreprise disposant d'un site web, d'une application mobile ou de comptes sur les réseaux sociaux doit se conformer à plusieurs obligations : mention légale de la dénomination sociale (AUSCGIE 2014), politique de confidentialité conforme à la loi sur les données personnelles, obtention du consentement des utilisateurs avant toute collecte de données, et respect des règles de publicité commerciale définies par le Code de la Communication (Loi n°019/2016). Le non-respect de ces obligations expose l'entreprise à des sanctions administratives et financières.\n\nOdillon élabore votre stratégie digitale complète en intégrant dès la conception le respect du cadre réglementaire gabonais. Nous créons et gérons vos contenus sur les réseaux sociaux, développons votre site web institutionnel, mettons en place les politiques de confidentialité et de gestion des cookies conformes à la législation, et formons vos équipes aux bonnes pratiques de communication numérique. Notre approche garantit une visibilité digitale optimale tout en vous prémunissant contre les risques juridiques liés à la non-conformité.\n\nLes sanctions pour non-respect de la protection des données personnelles peuvent inclure des amendes significatives, la suspension de l'activité de collecte, et une atteinte durable à la réputation de l'entreprise. Dans un environnement numérique en pleine structuration au Gabon, la conformité constitue un avantage concurrentiel majeur qui renforce la confiance de vos clients et partenaires.",
            impact: "Visibilité digitale optimisée dans le respect de la vie privée"
          },
          {
            title: "Communication de crise",
            content: "La gestion de crise médiatique au Gabon s'inscrit dans un cadre réglementaire défini par la Loi n°014/2023 portant réorganisation de la Haute Autorité de la Communication (HAC). Cette loi confère à la HAC des pouvoirs de sanction étendus : elle peut prononcer des avertissements, des suspensions temporaires et des retraits de licences à l'encontre des médias et des acteurs de la communication qui contreviennent à la réglementation. Toute entreprise confrontée à une crise médiatique doit donc tenir compte de ce cadre institutionnel dans sa stratégie de réponse.\n\nUne crise de communication peut prendre des formes multiples : bad buzz sur les réseaux sociaux, article de presse défavorable, conflit social médiatisé, mise en cause réglementaire ou judiciaire, incident environnemental ou sanitaire. Dans chaque cas, la réaction de l'entreprise doit être rapide, mesurée et conforme aux obligations légales. Le Code de la Communication (Loi n°019/2016) encadre le droit de réponse et les conditions de rectification des informations erronées, tandis que la loi sur la protection des données personnelles (Loi n°001/2011 modifiée par la Loi n°025/2023) impose des obligations spécifiques en cas de violation de données.\n\nLa préparation en amont est la clé d'une gestion de crise efficace. Elle passe par l'identification des risques spécifiques à votre secteur d'activité, l'élaboration de scénarios de crise, la rédaction de messages de communication pré-approuvés, la désignation de porte-paroles formés et la mise en place de procédures d'alerte et d'escalade. Les entreprises soumises à des obligations de publication légale (AUSCGIE 2014) doivent également anticiper les implications d'une crise sur leurs obligations déclaratives au RCCM et au Journal Officiel.\n\nOdillon déploie une méthodologie de gestion de crise éprouvée et adaptée au contexte gabonais. Nous réalisons un audit de vulnérabilité, élaborons votre plan de communication de crise, formons vos porte-paroles aux techniques de media training, et assurons un accompagnement en temps réel lors des situations de crise. Nos protocoles intègrent les relations avec les autorités de régulation (HAC, APDPVP) et les procédures de communication auprès des parties prenantes : collaborateurs, clients, partenaires, investisseurs et médias.\n\nL'absence de préparation à la crise peut avoir des conséquences dévastatrices : perte de confiance des clients et partenaires, dépréciation de la valeur de l'entreprise, sanctions réglementaires, et contentieux judiciaires prolongés. A l'inverse, une gestion de crise maîtrisée peut transformer une situation adverse en opportunité de renforcer la crédibilité et la résilience de votre organisation.",
            impact: "Protection de la réputation et maîtrise du cadre réglementaire"
          },
          {
            title: "Communication médiatique",
            content: "Le paysage médiatique gabonais est en pleine structuration sous l'impulsion de la Haute Autorité de la Communication (HAC), réorganisée par la Loi n°014/2023. En 2024, la HAC a recensé 169 médias en ligne opérant au Gabon, mais seulement 29 d'entre eux sont en règle avec la réglementation en vigueur. Ce constat souligne l'importance pour les entreprises de sélectionner avec discernement les canaux médiatiques à travers lesquels elles communiquent, afin de préserver leur crédibilité et d'éviter toute association avec des médias non conformes.\n\nLe Code de la Communication (Loi n°019/2016) encadre les relations entre les entreprises et les médias. Il définit les conditions d'exercice de la liberté de presse, le droit de réponse (délai de publication, conditions de forme), les règles de la publicité commerciale et les obligations des annonceurs. Toute entreprise qui communique via les médias doit s'assurer que ses partenaires médiatiques disposent des autorisations requises et opèrent dans le respect de la réglementation supervisée par la HAC.\n\nLes relations presse et relations publiques au Gabon présentent des spécificités qu'il est essentiel de maîtriser. Le tissu médiatique local comprend des médias d'État, des médias privés et un nombre croissant de médias en ligne. Les obligations de publication légale prévues par l'AUSCGIE 2014 (annonces au Journal Officiel pour les modifications statutaires, convocations d'assemblées générales conformément à l'article 516) s'ajoutent aux actions de communication volontaire. La rectification au RCCM dans un délai de trente jours pour toute modification statutaire implique également une communication coordonnée entre les volets juridique et médiatique.\n\nOdillon gère l'ensemble de vos relations médiatiques avec une expertise spécifique du paysage gabonais. Nous identifions les médias agréés et conformes les plus pertinents pour votre secteur, rédigeons vos communiqués de presse et dossiers de presse, organisons vos conférences de presse et événements médiatiques, et assurons le suivi des retombées. Notre carnet d'adresses couvre les principaux médias nationaux, les correspondants de la presse internationale présents à Libreville, et les influenceurs digitaux reconnus et conformes à la réglementation de la HAC.\n\nCommuniquer via des médias non conformes expose l'entreprise à des risques réputationnels importants : association avec des contenus non vérifiés, absence de droit de réponse effectif, et potentielle mise en cause par les autorités de régulation. En travaillant exclusivement avec des canaux vérifiés et agréés, vous garantissez à votre communication une crédibilité maximale et une diffusion auprès d'audiences qualifiées.",
            impact: "Couverture médiatique positive auprès de médias fiables et conformes"
          }
        ]
      }
    ],
  legalReferences: [
    { title: "AUSCGIE révisé 2014", description: "Obligations de publication des sociétés", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/AUSCGIE-2014.pdf", type: "pdf" },
    { title: "OAPI - Accord de Bangui révisé", description: "Protection de la propriété intellectuelle en Afrique", url: "https://www.oapi.int/index.php/fr/", type: "link" }
  ]
  }
