import { ServiceData } from "./types"

export const entreprenariatService: ServiceData = {
    id: "entreprenariat",
    icon: "Rocket",
    title: "Entreprenariat",
    color: "#00a795",
    gradient: "from-[#00a795]/20 via-[#00a795]/10 to-transparent",
    tagline: "Accompagnement Entrepreneurial",
    description: "Création d'entreprise en moins de 48h au Gabon via le Guichet National de l'Investissement (ANPI-Gabon). Nous vous guidons dans le choix de la forme juridique OHADA et les formalités, de l'idée au lancement.",
    keyBenefits: [
      { icon: "Rocket", text: "Lancement sécurisé", detail: "Création et structuration" },
      { icon: "Target", text: "Stratégie adaptée", detail: "Business model validé" },
      { icon: "Lightbulb", text: "Innovation", detail: "Idées concrétisées" }
    ],
    workflow: [
      { step: "1", title: "Idéation", description: "Validation de votre concept et étude de faisabilité", icon: "Lightbulb" },
      { step: "2", title: "Structuration", description: "Définition du modèle économique et de la stratégie", icon: "Target" },
      { step: "3", title: "Lancement", description: "Accompagnement dans la création et les démarches", icon: "Rocket" },
      { step: "4", title: "Croissance", description: "Suivi et accompagnement dans le développement", icon: "TrendingUp" }
    ],
    services: [
      {
        icon: "Rocket",
        name: "Accompagnement à la Création d'Entreprise",
        slug: "creation-entreprise",
        tagline: "De l'idée au projet concret",
        description: "Accompagnement complet dans la création de votre entreprise au Gabon, conformément au droit OHADA (AUSCGIE 2014, AUDCG 2010) et aux dispositifs du Guichet National de l'Investissement.",
        details: [
          {
            title: "Étude de faisabilité et validation du concept",
            content: "L'étude de faisabilité constitue le socle incontournable de tout projet entrepreneurial au Gabon. Elle s'inscrit dans le cadre comptable défini par l'Acte Uniforme relatif au Droit Comptable et à l'Information Financière (AUDCIF) révisé en 2017, qui impose le référentiel SYSCOHADA pour l'ensemble des entités économiques de l'espace OHADA. Ce cadre normatif garantit la fiabilité et la comparabilité des projections financières présentées aux partenaires et investisseurs.\n\nNotre analyse couvre l'ensemble des dimensions du projet : étude de marché sectorielle au Gabon et dans la sous-région CEMAC, analyse concurrentielle détaillée, évaluation des barrières à l'entrée réglementaires et financières, et construction de prévisions financières sur trois à cinq ans (compte de résultat prévisionnel, bilan, plan de trésorerie). Chaque projection intègre les paramètres fiscaux gabonais en vigueur, notamment l'Impôt sur les Sociétés à 30%, la TVA à 18%, ainsi que les charges sociales patronales (CNSS 18% et CNAMGS 4,1%).\n\nUn volet stratégique essentiel de notre étude consiste à identifier dès l'origine les dispositifs d'incitation à l'investissement dont votre projet peut bénéficier. La Charte des Investissements (Loi n°15/98 du 23 juillet 1998) offre des avantages significatifs : exonération d'IS pendant les trois premières années d'activité, possibilité d'amortissements dégressifs, et suspension de TVA sur les investissements de démarrage. Pour les projets industriels, la Zone Industrielle Spéciale de Nkok (Loi n°036/2018) propose des exonérations fiscales et douanières pouvant s'étendre jusqu'à cinq ans.\n\nOdillon intègre également dans son analyse les dispositifs spécifiques aux PME gabonaises. La Loi n°008/2018 relative à la promotion des PME prévoit une exonération d'IS pendant cinq ans pour les entreprises agréées, sous condition que les nationaux détiennent au moins 51% du capital. Notre étude évalue systématiquement l'éligibilité de votre projet à cet agrément et en quantifie l'impact financier sur votre plan d'affaires.",
            impact: "Risques identifiés et opportunités fiscales exploitées dès le départ"
          },
          {
            title: "Élaboration du business plan",
            content: "Le business plan est le document de référence qui traduit votre vision entrepreneuriale en projections financières crédibles et en stratégie opérationnelle concrète. Dans l'espace CEMAC et OHADA, ce document doit impérativement respecter le référentiel SYSCOHADA (AUDCIF 2017) pour être recevable par les institutions financières, les banques commerciales régulées par la COBAC, et les organismes de financement internationaux tels que l'IFC, présent au Gabon.\n\nNotre équipe construit un business plan complet intégrant l'ensemble des états financiers prévisionnels exigés : compte de résultat prévisionnel sur cinq exercices, bilan prévisionnel, tableau des flux de trésorerie, plan de financement et analyse du seuil de rentabilité. Chaque projection incorpore avec précision les paramètres fiscaux gabonais actuels : Impôt sur les Sociétés à 30%, TVA à 18%, contribution des patentes, taxe complémentaire sur les salaires (TCS), ainsi que l'ensemble des charges sociales obligatoires (CNSS à 23% dont 18% patronal depuis janvier 2026, CNAMGS à 6,1% dont 4,1% patronal).\n\nLe plan d'affaires intègre systématiquement les dispositifs d'aide aux PME gabonaises. La Loi n°008/2018 offre une exonération d'IS pendant cinq ans aux entreprises agréées PME, à condition que les nationaux détiennent au moins 51% du capital social. L'agrément, d'une durée de cinq ans renouvelable, ouvre également l'accès à des marchés publics réservés et à des conditions de financement préférentielles. Notre business plan quantifie précisément l'impact de ces avantages sur la trésorerie et la rentabilité de votre projet.\n\nAu-delà des chiffres, nous élaborons un narratif stratégique solide : analyse SWOT contextualisée à l'environnement gabonais, stratégie commerciale adaptée aux réalités du marché local et sous-régional, plan de ressources humaines conforme au Code du Travail (Loi n°022/2021), et calendrier de déploiement réaliste tenant compte des délais administratifs. Ce document devient votre outil de pilotage stratégique autant que votre passeport pour le financement.\n\nOdillon vous accompagne également dans la présentation de votre business plan aux partenaires financiers. Nous préparons les dossiers de demande de garantie auprès de la Société de Garantie du Gabon (SGG), qui couvre 50% à 75% du montant du crédit (jusqu'à 75% pour les femmes entrepreneures), et nous vous orientons vers les lignes de crédit dédiées, comme le partenariat ANPI-Gabon/COFINA doté de 500 millions FCFA pour le financement des PME.",
            impact: "Crédibilité auprès des partenaires, investisseurs et institutions financières"
          },
          {
            title: "Choix de la forme juridique",
            content: "Le choix de la forme juridique est une décision structurante qui engage l'avenir de votre entreprise, votre responsabilité personnelle et votre capacité à mobiliser des financements. Ce choix s'opère dans le cadre de l'Acte Uniforme relatif au droit des Sociétés Commerciales et du Groupement d'Intérêt Économique (AUSCGIE), révisé le 30 janvier 2014 et entré en vigueur le 5 mai 2014, qui harmonise le droit des sociétés dans les dix-sept États membres de l'OHADA.\n\nPlusieurs formes juridiques s'offrent à vous, chacune avec ses spécificités. La Société à Responsabilité Limitée (SARL, Art. 309 à 384 AUSCGIE) est la forme la plus répandue au Gabon : le capital minimum OHADA est fixé à 1 000 000 FCFA, mais le Gabon a instauré un régime simplifié permettant la création à partir de 100 000 FCFA seulement, rendant cette forme accessible aux petits entrepreneurs. La responsabilité des associés est limitée à leurs apports. La Société Anonyme (SA, Art. 385 à 853 AUSCGIE) convient aux projets d'envergure : le capital minimum est de 10 000 000 FCFA sans appel public à l'épargne (APE) et de 100 000 000 FCFA avec APE, avec des actions d'une valeur nominale minimale de 10 000 FCFA.\n\nLa Société par Actions Simplifiée (SAS, Art. 853-1 à 853-23 AUSCGIE), introduite lors de la révision de 2014, offre une souplesse remarquable : aucun capital minimum n'est imposé, les associés disposent d'une liberté statutaire maximale pour organiser la gouvernance, et la société peut être constituée par un seul associé (SASU) ou plusieurs. C'est la forme privilégiée par les startups et les investisseurs étrangers. D'autres options existent : la Société en Nom Collectif (SNC), sans capital minimum mais avec une responsabilité solidaire et indéfinie des associés, le Groupement d'Intérêt Économique (GIE) pour les activités accessoires entre entreprises existantes, ou encore le statut d'Entreprenant (Art. 30 à 44 de l'AUDCG 2010) pour les très petites activités ne dépassant pas les seuils réglementaires.\n\nOdillon réalise une analyse personnalisée de votre situation pour recommander la forme la plus adaptée. Nous prenons en compte votre projet d'activité, le nombre d'associés, le montant du capital disponible, votre tolérance au risque patrimonial, vos perspectives de croissance et de levée de fonds, ainsi que les implications fiscales et sociales de chaque option. Notre conseil intègre également la dimension pratique : obligations de gouvernance (assemblées générales, commissaire aux comptes obligatoire pour les SA), coûts de fonctionnement, et facilité de transmission ou de cession future des parts ou actions.",
            impact: "Structure juridique optimale pour votre projet et votre patrimoine"
          },
          {
            title: "Accompagnement aux formalités de création",
            content: "La création d'entreprise au Gabon a été considérablement simplifiée grâce à la mise en place de l'Agence Nationale de Promotion des Investissements (ANPI-Gabon), créée par le Décret n°311/PR/MPIHAT du 25 septembre 2014 en fusionnant trois anciens organismes. L'ANPI-Gabon opère comme guichet unique à travers le Guichet Numérique de l'Investissement (GNI), une plateforme en ligne qui centralise l'ensemble des formalités de création et permet d'obtenir l'immatriculation complète de votre société en moins de 48 heures.\n\nLe processus de création via le GNI comprend plusieurs étapes que nous prenons intégralement en charge : remplissage du formulaire unique en ligne, dépôt des pièces justificatives dématérialisées, et suivi du dossier jusqu'à l'obtention de l'immatriculation au Registre du Commerce et du Crédit Mobilier (RCCM, conformément aux Art. 19 et suivants de l'AUDCG 2010) et de l'attribution du Numéro d'Identification Fiscale (NIF). Les frais de création sont de 150 000 FCFA pour les personnes morales de nationalité gabonaise et de 300 000 FCFA pour les non-nationaux, hors frais de notaire le cas échéant.\n\nEn amont de l'immatriculation, Odillon assure la rédaction complète des statuts de votre société en stricte conformité avec l'AUSCGIE 2014. Chaque clause est adaptée à la forme juridique choisie et à vos besoins spécifiques : objet social, répartition du capital, modalités de gouvernance, conditions de cession des parts ou actions, clauses d'agrément, et dispositions relatives à la dissolution. Pour les SAS, nous exploitons pleinement la liberté statutaire offerte par les articles 853-1 à 853-23 pour concevoir des mécanismes de gouvernance sur mesure.\n\nNotre accompagnement ne s'arrête pas à l'obtention du RCCM. Nous veillons également à l'accomplissement de toutes les formalités complémentaires indispensables au démarrage effectif de votre activité : déclaration d'existence auprès de la Direction Générale des Impôts, immatriculation à la CNSS et à la CNAMGS en tant qu'employeur, ouverture du compte bancaire professionnel, obtention des autorisations sectorielles éventuelles, et mise en conformité avec les obligations comptables du SYSCOHADA. L'article 19 de l'AUDCG 2010 impose par ailleurs que l'immatriculation au RCCM soit effectuée dans le mois suivant le début de l'activité, un délai que nous respectons scrupuleusement.",
            impact: "Entreprise créée rapidement et en totale conformité juridique"
          }
        ]
      },
      {
        icon: "TrendingUp",
        name: "Développement et Croissance",
        slug: "developpement-croissance",
        tagline: "Accélérez votre développement",
        description: "Accompagnement dans la croissance de votre entreprise en exploitant les dispositifs de soutien aux PME gabonaises et les avantages fiscaux disponibles.",
        details: [
          {
            title: "Stratégie de développement",
            content: "La stratégie de développement d'une entreprise au Gabon doit s'appuyer sur une connaissance fine de l'écosystème réglementaire et des dispositifs incitatifs mis en place par l'État. La Charte des Investissements, instituée par la Loi n°15/98 du 23 juillet 1998, constitue le socle du cadre incitatif gabonais. Elle offre aux entreprises éligibles des avantages substantiels : exonération d'Impôt sur les Sociétés pendant les trois premières années d'exploitation, possibilité de pratiquer des amortissements dégressifs accélérés sur les équipements productifs, et suspension de TVA sur les biens d'investissement acquis lors de la phase de démarrage ou d'extension.\n\nPour les entreprises à vocation industrielle ou de transformation, la Zone Industrielle Spéciale (ZIS) de Nkok, régie par la Loi n°036/2018, offre un cadre encore plus attractif. Les entreprises installées dans cette zone bénéficient d'exonérations fiscales pouvant s'étendre jusqu'à cinq ans (un périmètre revu à la suite des recommandations du FMI en 2021), d'une exemption de droits de douane sur les importations de matières premières et d'équipements, ainsi que d'infrastructures industrielles modernes. L'implantation en ZIS est particulièrement pertinente pour les projets de transformation locale des ressources naturelles gabonaises.\n\nLe dispositif de soutien aux PME, instauré par la Loi n°008/2018, représente un levier de croissance majeur pour les entreprises à capitaux majoritairement gabonais. L'agrément PME, délivré pour une durée de cinq ans renouvelable, est réservé aux entreprises dont les nationaux détiennent au moins 51% du capital social. Il ouvre droit à une exonération d'IS pendant cinq ans, à un accès privilégié aux marchés publics (quotas réservés), et à des facilités de financement via les partenariats institutionnels. Odillon vous accompagne dans la constitution du dossier d'agrément et le suivi du processus auprès des autorités compétentes.\n\nNotre approche stratégique combine ces dispositifs légaux avec une analyse opérationnelle rigoureuse : identification des marchés porteurs au Gabon et dans la zone CEMAC, évaluation des partenariats stratégiques possibles, optimisation de la chaîne de valeur, et planification des investissements en phase avec les cycles d'exonération. Nous élaborons une feuille de route de croissance réaliste, assortie d'indicateurs de performance mesurables, qui maximise l'utilisation des avantages légaux tout en construisant un avantage concurrentiel durable.",
            impact: "Croissance accélérée grâce aux dispositifs d'aide et avantages fiscaux"
          },
          {
            title: "Recherche de financements",
            content: "L'accès au financement reste l'un des défis majeurs pour les entrepreneurs gabonais, mais l'écosystème financier offre aujourd'hui des dispositifs diversifiés que notre cabinet maîtrise parfaitement. La Société de Garantie du Gabon (SGG) joue un rôle central en facilitant l'accès au crédit bancaire : elle garantit entre 50% et 75% du montant des emprunts contractés par les PME auprès des banques commerciales, réduisant ainsi significativement le risque perçu par les établissements prêteurs. Un dispositif spécifique porte la garantie à 75% pour les femmes entrepreneures, traduisant la volonté publique de promouvoir l'entrepreneuriat féminin au Gabon.\n\nLe partenariat stratégique entre l'ANPI-Gabon et COFINA a mis à disposition une enveloppe de 500 millions FCFA dédiée au financement des PME gabonaises. Ce fonds cible particulièrement les entreprises en phase de démarrage ou de premier développement qui ne disposent pas encore du track record exigé par les banques commerciales classiques. Les conditions d'accès sont plus souples que le crédit bancaire traditionnel, avec des procédures d'instruction accélérées et des garanties adaptées à la réalité des petites entreprises.\n\nAu-delà de ces dispositifs nationaux, le secteur bancaire gabonais, régulé par la Commission Bancaire de l'Afrique Centrale (COBAC) dans le cadre de la CEMAC, propose des lignes de crédit aux entreprises. Les principales banques commerciales de la place offrent du crédit d'investissement, du crédit de fonctionnement, des facilités de caisse et des lignes d'escompte. Par ailleurs, des bailleurs internationaux sont actifs au Gabon : l'International Finance Corporation (IFC, filiale de la Banque Mondiale) finance directement des projets privés, et des institutions comme la Banque Africaine de Développement (BAD) interviennent via des lignes de refinancement.\n\nOdillon vous accompagne de bout en bout dans la recherche de financements. Nous réalisons un diagnostic de vos besoins financiers, identifions les sources les plus pertinentes compte tenu de votre profil et de votre secteur d'activité, et montons intégralement les dossiers de demande : business plan conforme au SYSCOHADA, prévisions de trésorerie, garanties proposées, et documentation juridique complète. Notre réseau de contacts dans les institutions financières gabonaises nous permet d'accélérer le traitement de vos dossiers et de négocier les meilleures conditions.",
            impact: "Accès facilité aux financements avec garanties institutionnelles"
          },
          {
            title: "Accompagnement opérationnel",
            content: "Le passage de la création au fonctionnement effectif de l'entreprise constitue une phase critique où de nombreux entrepreneurs se trouvent confrontés à la complexité des obligations réglementaires gabonaises. L'Acte Uniforme relatif au Droit Comptable et à l'Information Financière (AUDCIF 2017) impose à toute entité économique de l'espace OHADA la tenue d'une comptabilité conforme au référentiel SYSCOHADA : journal, grand livre, balance, et établissement des états financiers annuels (bilan, compte de résultat, tableau des flux de trésorerie, notes annexes). Odillon prend en charge l'intégralité de ces obligations comptables pour vous permettre de vous concentrer sur votre activité.\n\nSur le plan fiscal, les obligations sont multiples et leurs échéances strictes. La TVA (18%) doit faire l'objet de déclarations mensuelles, l'Impôt sur les Sociétés (30%) est déclaré annuellement avec des acomptes trimestriels, la Taxe Complémentaire sur les Salaires (TCS) et l'IRPP retenu à la source sont déclarés mensuellement avec une échéance au 20 du mois suivant, et la contribution des patentes est annuelle. Le non-respect de ces échéances expose l'entreprise à des pénalités de retard, des majorations, voire des procédures de redressement fiscal. Notre équipe assure un suivi rigoureux de chaque échéance et produit les déclarations dans les délais impartis.\n\nDès le premier recrutement, l'entreprise entre dans le champ du Code du Travail gabonais (Loi n°022/2021) et des obligations sociales associées. L'employeur doit s'immatriculer auprès de la CNSS et de la CNAMGS, établir des contrats de travail conformes (CDI ou CDD limité à deux ans selon l'Art. 23), déclarer chaque salarié, et verser mensuellement les cotisations sociales : CNSS à 23% (dont 18% patronal et 5% salarial, plafonné à 1 500 000 FCFA/mois depuis le Décret n°0487/PR/MASI du 18 décembre 2025) et CNAMGS à 6,1% (dont 4,1% patronal et 2% salarial, plafonné à 2 500 000 FCFA/mois). Les Déclarations Trimestrielles des Salaires (DTS) doivent être transmises à la CNSS au plus tard le 30 du mois suivant la fin du trimestre.\n\nOdillon assure un accompagnement opérationnel global qui couvre l'ensemble de ces dimensions. Nous mettons en place les processus administratifs, comptables et sociaux adaptés à la taille et au secteur de votre entreprise, formons vos équipes internes aux bonnes pratiques, et assurons un suivi régulier pour garantir une conformité permanente. Notre objectif est de vous offrir la sérénité administrative nécessaire pour vous consacrer pleinement au développement commercial de votre activité.",
            impact: "Performance opérationnelle et conformité réglementaire dès le premier jour"
          }
        ]
      }
    ],
  legalReferences: [
    { title: "AUSCGIE révisé 2014", description: "Formes juridiques : SARL, SA, SAS, SNC, GIE", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/AUSCGIE-2014.pdf", type: "pdf" },
    { title: "AUDCG révisé 2010", description: "Droit Commercial Général, RCCM, statut d'Entreprenant", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/AUDCG-2010.pdf", type: "pdf" },
    { title: "AUSCOOP 2010", description: "Acte Uniforme relatif aux Sociétés Coopératives", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/AUSCOOP-2010.pdf", type: "pdf" },
    { title: "Code Général des Impôts (CGI 2025)", description: "IS, TVA, patentes et fiscalité des entreprises", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/CGI-Gabon-2025.pdf", type: "pdf" },
    { title: "Code des Marchés Publics", description: "Accès aux marchés publics pour les PME", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/Code-Marches-Publics-Gabon.pdf", type: "pdf" },
    { title: "Charte des Investissements", description: "Loi n°15/98 - Avantages fiscaux pour les investisseurs", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/Charte-Investissements-Gabon-1998.pdf", type: "pdf" },
    { title: "Loi PME n°008/2018", description: "Promotion des PME - Agrément et avantages", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/Loi-PME-Gabon-2018.pdf", type: "pdf" },
    { title: "GNI - ANPI Gabon", description: "Guichet Numérique de l'Investissement - Création d'entreprise", url: "https://www.gni-anpigabon.com/", type: "link" }
  ]
  }
