import { ServiceData } from "./types"

export const financesService: ServiceData = {
    id: "finances",
    icon: "TrendingUp",
    title: "Finances",
    color: "#39837a",
    gradient: "from-[#39837a]/20 via-[#39837a]/10 to-transparent",
    tagline: "Conseils Financiers",
    description: "Nos conseillers financiers sont à l'écoute de vos besoins en investissements et en accompagnement comptable.",
    keyBenefits: [
      { icon: "TrendingUp", text: "Croissance accélérée", detail: "Stratégie financière optimale" },
      { icon: "Target", text: "Financement facilité", detail: "Accès aux meilleures sources" },
      { icon: "BarChart3", text: "Performance mesurée", detail: "KPIs et tableaux de bord" }
    ],
    workflow: [
      { step: "1", title: "Diagnostic", description: "Analyse approfondie de votre situation financière actuelle", icon: "Search" },
      { step: "2", title: "Stratégie", description: "Élaboration du business plan et de la stratégie financière", icon: "Target" },
      { step: "3", title: "Exécution", description: "Mise en place des outils financiers et levée de fonds", icon: "TrendingUp" },
      { step: "4", title: "Pilotage", description: "Reporting, tableaux de bord et suivi des indicateurs", icon: "BarChart3" }
    ],
    services: [
      {
        icon: "TrendingUp",
        name: "Conseil Financier",
        slug: "conseil-financier",
        tagline: "Financez votre ambition",
        description: "Accompagnement complet dans la structuration et la recherche de financements.",
        details: [
          {
            title: "Conseil Financier pour les opérations de levée de fonds sous forme de Dette ou d'Actions",
            content: "Dans l'espace économique CEMAC, les entreprises disposent de plusieurs instruments de financement encadrés par des réglementations strictes. La Commission Bancaire de l'Afrique Centrale (COBAC) fixe les normes prudentielles auxquelles sont soumises les banques commerciales, tandis que le marché financier régional de la BVMAC offre depuis sa fusion en 2019 un cadre unifié pour les émissions obligataires et les introductions en bourse à l'échelle de la sous-région.\n\nConcrètement, la levée de fonds peut prendre plusieurs formes : la dette bancaire classique (crédit d'investissement, ligne de crédit revolving, crédit-bail), l'émission d'obligations sur le marché BVMAC, la prise de participation au capital par des investisseurs privés ou institutionnels, ou encore les subventions d'investissement accordées par l'État ou les organismes multilatéraux. Chaque instrument obéit à des conditions d'éligibilité, des coûts et des contraintes de remboursement spécifiques que nous analysons en détail.\n\nPar ailleurs, la Charte des Investissements (Loi n°15/98) prévoit un régime d'exonération de l'impôt sur les sociétés durant les trois premières années d'activité pour les entreprises nouvellement créées qui remplissent certains critères d'investissement et de création d'emplois. La Zone Industrielle Spéciale de Nkok (Loi n°036/2018) offre quant à elle des exonérations fiscales et douanières pouvant aller jusqu'à cinq ans, sous réserve des ajustements recommandés par le FMI lors de la revue de 2021.\n\nOdillon vous accompagne dans l'identification de la structure de financement optimale, en combinant les différentes sources disponibles et en maximisant les avantages fiscaux légaux. Nous préparons les dossiers de demande, négocions avec les établissements financiers et structurons l'opération de bout en bout pour sécuriser votre levée de fonds dans les meilleures conditions.",
            impact: "Accès aux meilleures sources de financement selon les réglementations OHADA et CEMAC"
          },
          {
            title: "Conseil en Investissement",
            content: "Le cadre fiscal gabonais impose un impôt sur les sociétés (IS) de 35 % sur les bénéfices nets, une taxe sur la valeur ajoutée (TVA) de 18 % et un impôt minimum forfaitaire correspondant à 1 % du chiffre d'affaires ou 500 000 FCFA, le montant le plus élevé étant retenu. Ces paramètres conditionnent directement la rentabilité de tout projet d'investissement et doivent être intégrés dès l'étude de faisabilité.\n\nLa Charte des Investissements (Loi n°15/98) offre toutefois des mécanismes d'allègement significatifs : exonération d'IS pendant les trois premières années pour les investissements éligibles, réductions de droits de douane sur les équipements importés, et crédit d'impôt pour la création d'emplois locaux. La Zone Industrielle Spéciale de Nkok, régie par la Loi n°036/2018, propose un régime encore plus avantageux avec des exonérations fiscales et douanières pouvant s'étendre jusqu'à cinq ans, bien que le FMI ait recommandé en 2021 un encadrement plus strict de ces avantages.\n\nPour chaque opportunité d'investissement, Odillon réalise une analyse financière approfondie : calcul du taux de rendement interne (TRI), valeur actuelle nette (VAN), délai de récupération du capital investi, et analyse de sensibilité aux variations des paramètres clés. Nous intégrons systématiquement les risques de change (FCFA arrimé à l'euro), les risques sectoriels et le cadre réglementaire spécifique à chaque activité.\n\nNotre valeur ajoutée réside dans notre connaissance fine de l'environnement des affaires gabonais et des acteurs institutionnels. Nous identifions les montages juridiques et fiscaux les plus adaptés à votre projet, et vous guidons dans les démarches auprès de l'ANPI-Gabon (Agence Nationale de Promotion des Investissements) pour bénéficier des régimes préférentiels auxquels vous êtes éligible.",
            impact: "ROI maximisé grâce à une optimisation fiscale légale"
          },
          {
            title: "Rédaction des Procédures",
            content: "L'Acte Uniforme relatif au Droit Comptable et à l'Information Financière (AUDCIF), adopté le 26 janvier 2017 et entré en vigueur le 1er janvier 2018, impose à toutes les entreprises de l'espace OHADA de tenir leur comptabilité selon le SYSCOHADA révisé. Ce référentiel, structuré autour de 9 classes de comptes (classes 1 à 5 pour le bilan, classes 6 et 7 pour les charges et produits, classe 8 pour les engagements hors bilan, classe 9 pour la comptabilité analytique), exige des procédures comptables formalisées et documentées.\n\nNos équipes élaborent l'ensemble des procédures nécessaires au bon fonctionnement de votre service comptable et financier : procédure d'enregistrement des opérations courantes, procédure de rapprochement bancaire, procédure de gestion des immobilisations, procédure de clôture mensuelle et annuelle, procédure de validation et d'autorisation des dépenses par seuils de montant, ainsi que les procédures de contrôle interne destinées à prévenir la fraude et les erreurs.\n\nChaque procédure est rédigée sous forme de logigramme et de fiche descriptive précisant les acteurs impliqués, les étapes séquentielles, les documents supports, les délais de traitement et les points de contrôle. Les procédures de reporting intègrent les états financiers obligatoires du SYSCOHADA : le Bilan, le Compte de résultat, le Tableau des flux de trésorerie et le TAFIRE (Tableau Financier des Ressources et des Emplois), ce dernier étant spécifique au référentiel OHADA.\n\nOdillon assure également la formation de vos équipes à l'application de ces procédures et met en place un dispositif de mise à jour périodique pour garantir la conformité permanente de votre organisation comptable face aux évolutions réglementaires.",
            impact: "Efficacité opérationnelle et conformité comptable permanente"
          },
          {
            title: "Rédaction du Business Plan",
            content: "Le business plan constitue le document de référence pour tout projet de création, de développement ou de recherche de financement. Au Gabon, les bailleurs de fonds, les banques soumises aux normes COBAC et les investisseurs institutionnels exigent un dossier conforme aux standards de présentation de la zone CEMAC, intégrant les spécificités du référentiel comptable SYSCOHADA révisé (AUDCIF 2017).\n\nNos experts élaborent des prévisions financières détaillées sur un horizon de 3 à 5 ans, comprenant : le compte de résultat prévisionnel (avec ventilation des charges par nature selon les classes 6 et 7 du plan OHADA), le bilan prévisionnel, le plan de trésorerie mensuel et le TAFIRE (Tableau Financier des Ressources et des Emplois), état financier spécifique au SYSCOHADA qui retrace les flux de ressources et d'emplois de l'exercice.\n\nChaque projection intègre les paramètres fiscaux en vigueur au Gabon : un impôt sur les sociétés de 35 % calculé sur le bénéfice fiscal, une TVA de 18 % avec ses mécanismes de récupération, l'impôt minimum forfaitaire de 1 % du chiffre d'affaires ou 500 000 FCFA (le plus élevé), les cotisations sociales patronales (CNSS à 18 % et CNAMGS à 4,1 %), ainsi que les échéances déclaratives (TVA avant le 20 de chaque mois, IS avant le 1er août). Ces éléments permettent de construire un modèle financier réaliste et crédible.\n\nOdillon vous accompagne également dans la rédaction de la partie narrative du business plan : présentation de l'équipe dirigeante, analyse du marché gabonais, positionnement concurrentiel, stratégie commerciale et plan d'action opérationnel. Le document final est conçu pour répondre aux exigences des comités de crédit bancaires et des fonds d'investissement de la zone CEMAC.",
            impact: "Business plan conforme aux exigences des bailleurs et investisseurs de la zone CEMAC"
          },
          {
            title: "Accompagnement dans l'élaboration du Budget",
            content: "La construction budgétaire est un exercice fondamental de pilotage financier qui, au Gabon, doit impérativement intégrer les spécificités du calendrier fiscal et social. Les déclarations de TVA doivent être déposées avant le 20 de chaque mois, la déclaration d'impôt sur les sociétés avant le 1er août, et les cotisations CNSS sont exigibles trimestriellement. Ces échéances structurent directement le budget de trésorerie et les besoins en fonds de roulement.\n\nNous accompagnons votre équipe financière dans l'élaboration de trois budgets complémentaires et articulés : le budget d'exploitation (prévision des revenus et des charges courantes ventilées selon les classes 6 et 7 du plan comptable SYSCOHADA), le budget d'investissement (acquisitions d'immobilisations, renouvellements, cessions programmées) et le budget de trésorerie (encaissements et décaissements prévisionnels mois par mois, incluant les décaissements fiscaux et sociaux obligatoires).\n\nChaque poste budgétaire est calibré en tenant compte des paramètres fiscaux applicables : IS à 35 %, TVA à 18 % (avec distinction entre TVA collectée et TVA déductible), cotisations patronales CNSS de 18 % plafonnées à 1 500 000 FCFA de salaire mensuel, cotisations CNAMGS de 4,1 %, et impôt minimum forfaitaire de 1 % du chiffre d'affaires. La Loi de Finances annuelle peut modifier ces taux, ce qui nécessite une veille réglementaire permanente.\n\nOdillon met en place un processus budgétaire itératif avec des révisions trimestrielles permettant d'ajuster les prévisions aux réalisations. Nous formons vos responsables opérationnels à la discipline budgétaire et instaurons un reporting d'écarts (réel vs. budget) qui alimente les décisions de gestion en temps réel.",
            impact: "Maîtrise des flux financiers et conformité permanente avec la Loi de Finances"
          },
          {
            title: "Mise en place des tableaux de bord",
            content: "Le pilotage financier efficace repose sur des indicateurs clés de performance (KPIs) directement dérivés des états financiers obligatoires du SYSCOHADA révisé : le Bilan (situation patrimoniale), le Compte de résultat (performance économique), le Tableau des flux de trésorerie (capacité de génération de cash) et le TAFIRE (équilibre entre ressources et emplois). Ces quatre états constituent le socle de tout tableau de bord financier conforme au référentiel OHADA.\n\nNos tableaux de bord intègrent les ratios de gestion essentiels : ratio de liquidité générale, ratio d'endettement, capacité d'autofinancement, besoin en fonds de roulement, rotation des stocks, délais de règlement clients et fournisseurs, marge brute d'exploitation et résultat net. Pour les entreprises en relation avec les établissements de crédit, nous ajoutons les ratios prudentiels exigés par la COBAC, notamment les ratios de solvabilité et de division des risques.\n\nChaque indicateur est présenté avec son seuil d'alerte, sa tendance et sa comparaison avec les données sectorielles disponibles au Gabon. Le tableau de bord inclut également le suivi des obligations fiscales et sociales avec un calendrier automatisé des échéances : déclarations TVA mensuelles, acomptes IS, cotisations CNSS trimestrielles, cotisations CNAMGS, et toute autre obligation issue de la Loi de Finances en vigueur.\n\nOdillon conçoit des tableaux de bord sur mesure, adaptés à votre secteur d'activité et à la taille de votre entreprise. Nous formons vos équipes à leur lecture et à leur utilisation comme outil d'aide à la décision, et assurons leur mise à jour en fonction des évolutions réglementaires et comptables de l'espace OHADA.",
            impact: "Pilotage financier en temps réel conforme aux standards OHADA"
          },
          {
            title: "Lobbying financier",
            content: "L'accès au financement en Afrique centrale repose largement sur la qualité des relations entretenues avec les acteurs du secteur financier. La zone CEMAC compte un nombre limité de banques commerciales, toutes soumises aux normes prudentielles de la COBAC (Commission Bancaire de l'Afrique Centrale), ce qui rend la connaissance de leurs critères d'octroi et de leurs procédures internes un atout déterminant pour toute entreprise en recherche de financement.\n\nAu-delà du système bancaire classique, le Gabon bénéficie de la présence d'acteurs financiers internationaux de premier plan. L'IFC (Société Financière Internationale, filiale du Groupe Banque Mondiale) est présente au Gabon depuis 2026 avec un portefeuille d'engagements de 117 millions USD, orienté vers le développement du secteur privé, les infrastructures et la diversification économique. La Banque Africaine de Développement, la BDEAC (Banque de Développement des États de l'Afrique Centrale) et les fonds d'investissement régionaux constituent également des sources de financement accessibles pour les projets structurants.\n\nOdillon a tissé au fil des années un réseau de relations privilégiées avec ces institutions financières nationales et internationales. Notre équipe connaît les interlocuteurs clés, les processus décisionnels internes et les critères d'éligibilité spécifiques de chaque bailleur. Cette connaissance intime de l'écosystème financier nous permet de vous orienter vers les sources de financement les plus adaptées à votre projet et d'optimiser vos chances de succès.\n\nNotre accompagnement en lobbying financier comprend la mise en relation avec les décideurs, la préparation des dossiers selon les standards de chaque institution, la participation aux négociations et le suivi post-octroi. Nous vous aidons également à diversifier vos sources de financement pour réduire votre dépendance à un seul partenaire financier.",
            impact: "Accès privilégié aux financements nationaux et internationaux"
          }
        ]
      }
    ],
  legalReferences: [
    { title: "AUDCIF 2017 (SYSCOHADA)", description: "Système Comptable OHADA révisé", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/AUDCIF-2017.pdf", type: "pdf" },
    { title: "Charte des Investissements", description: "Loi n°15/98 du 23 juillet 1998", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/Charte-Investissements-Gabon-1998.pdf", type: "pdf" },
    { title: "Loi PME n°008/2018", description: "Orientation de la politique nationale de promotion des PME", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/Loi-PME-Gabon-2018.pdf", type: "pdf" },
    { title: "Code Général des Impôts (CGI 2025)", description: "Code fiscal gabonais consolidé - Impôts directs et indirects", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/CGI-Gabon-2025.pdf", type: "pdf" }
  ]
  }
