import { ServiceData } from "./types"

export const formationsService: ServiceData = {
    id: "formations",
    icon: "GraduationCap",
    title: "Formations",
    color: "#39837a",
    gradient: "from-[#39837a]/20 via-[#39837a]/10 to-transparent",
    tagline: "Formation Professionnelle",
    description: "L'employeur est tenu de veiller au maintien et au développement des compétences de ses salariés (Code du Travail 2021). La Contribution à la Formation Professionnelle (CFP) de 0,50% de la masse salariale brute (Art. 95-96 CGI) finance ce dispositif.",
    keyBenefits: [
      { icon: "GraduationCap", text: "Montée en compétences", detail: "Savoir et savoir-faire" },
      { icon: "Users2", text: "Coaching personnalisé", detail: "Accompagnement individuel" },
      { icon: "Rocket", text: "Formats flexibles", detail: "Présentiel et en ligne" }
    ],
    workflow: [
      { step: "1", title: "Diagnostic", description: "Identification des besoins en formation et des compétences à développer", icon: "Search" },
      { step: "2", title: "Conception", description: "Élaboration de programmes de formation sur mesure adaptés à vos enjeux", icon: "Target" },
      { step: "3", title: "Animation", description: "Déploiement des formations avec des méthodes pédagogiques innovantes", icon: "GraduationCap" },
      { step: "4", title: "Évaluation", description: "Mesure de l'impact des formations et suivi des acquis", icon: "Award" }
    ],
    services: [
      {
        icon: "GraduationCap",
        name: "Programmes de Formation",
        slug: "programmes-formation",
        tagline: "Développez vos talents",
        description: "Des programmes de formation reconnus par le cadre légal gabonais, adaptés à tous les niveaux, pour répondre à l'obligation de l'employeur de maintenir et développer les compétences de ses salariés.",
        details: [
          {
            title: "Master Class",
            content: "Le Code du Travail gabonais de 2021 (Loi n°022/2021) consacre l'obligation pour l'employeur de veiller au maintien et au développement des compétences de ses salariés tout au long de leur carrière. Cette obligation légale s'accompagne du financement par la Contribution à la Formation Professionnelle (CFP), fixée à 0,50 % de la masse salariale brute conformément aux articles 95 et 96 du Code Général des Impôts. Les Master Class constituent un format privilégié pour répondre à cette exigence dans des délais maîtrisés.\n\nNos Master Class sont des sessions intensives de deux à cinq jours, animées par des experts reconnus dans leur domaine. Elles couvrent des thématiques stratégiques et managériales essentielles : gouvernance d'entreprise selon les normes de l'Acte Uniforme OHADA sur les sociétés commerciales (AUSCGIE 2014), droit du travail gabonais, management financier conforme au référentiel SYSCOHADA, et leadership organisationnel. Chaque session est structurée autour de cas pratiques issus du contexte économique gabonais et sous-régional.\n\nCe format est reconnu par la Direction Générale de la Formation Professionnelle (DGFP), placée sous la tutelle du Ministère du Travail. La DGFP supervise la qualité des programmes de formation et veille à leur conformité avec les objectifs nationaux de développement des compétences. L'Agence Nationale de Formation et de Perfectionnement Professionnels (ANFPP), créée par l'Ordonnance n°48/77/PR du 28 août 1977, participe également à la structuration de l'offre de formation au niveau national.\n\nOdillon conçoit chaque Master Class sur mesure en fonction de vos enjeux stratégiques. Nous réalisons un diagnostic préalable de vos besoins, élaborons un programme adapté à votre secteur d'activité, et assurons un suivi post-formation pour ancrer durablement les acquis. Nos formateurs combinent expertise technique et connaissance approfondie de l'environnement juridique et économique gabonais, garantissant un transfert de compétences directement opérationnel.",
            impact: "Acquisition rapide de compétences de haut niveau certifiées"
          },
          {
            title: "Coaching individuel professionnel",
            content: "La Loi n°022/2021 portant Code du Travail en République Gabonaise impose à l'employeur une obligation d'adaptation des compétences de ses collaborateurs face aux évolutions technologiques, organisationnelles et économiques. Au-delà de la formation collective, le coaching individuel professionnel répond à cette exigence de manière ciblée en offrant un accompagnement sur mesure, particulièrement adapté aux dirigeants, cadres supérieurs et managers en prise de poste.\n\nLe coaching professionnel se distingue de la formation classique par son approche personnalisée et progressive. Il s'agit d'un processus structuré, généralement étalé sur trois à six mois, au cours duquel un coach certifié travaille en face-à-face avec le bénéficiaire sur des objectifs précis : renforcement du leadership, gestion du changement, développement de la posture managériale, prise de décision stratégique ou encore gestion des conflits. Chaque parcours est défini en amont sur la base d'un diagnostic individuel approfondi.\n\nDans le contexte gabonais, le coaching individuel s'inscrit dans les pratiques RH modernes encouragées par les pouvoirs publics. Le financement peut être imputé sur la Contribution à la Formation Professionnelle (CFP) de 0,50 % de la masse salariale brute (Art. 95-96 CGI), au même titre que les autres actions de développement des compétences. Les conventions collectives sectorielles peuvent également prévoir des dispositions spécifiques relatives au congé de formation dont peut bénéficier le salarié coaché.\n\nOdillon met à votre disposition des coachs expérimentés, formés aux méthodes internationales et dotés d'une connaissance fine du tissu économique gabonais et de la zone CEMAC. Nous définissons avec vous les indicateurs de progression, assurons un reporting régulier auprès de la direction des ressources humaines, et garantissons la confidentialité totale des échanges. Le coaching se déroule en présentiel à Libreville ou à distance selon les besoins, avec une flexibilité horaire adaptée aux contraintes des dirigeants.\n\nEn l'absence de coaching adapté, les entreprises s'exposent à un turnover élevé des cadres, à des prises de poste difficiles et à une perte de performance managériale. Le retour sur investissement du coaching est démontré : amélioration mesurable de la productivité, réduction des conflits internes et fidélisation des talents clés.",
            impact: "Développement ciblé et progression mesurable des leaders"
          },
          {
            title: "Formations en ligne",
            content: "Le système de formation professionnelle gabonais connaît une mutation profonde avec la modernisation annoncée en 2025 par le Ministère du Travail, visant à adapter le dispositif national aux exigences du marché du XXIe siècle. Cette modernisation passe notamment par le développement du e-learning et des formats d'apprentissage à distance, qui permettent de démocratiser l'accès à la formation au-delà des contraintes géographiques, particulièrement pertinent dans un pays où de nombreuses entreprises opèrent dans des zones éloignées de Libreville.\n\nNos modules e-learning sont conçus pour offrir une expérience pédagogique complète et accessible à tout moment depuis n'importe quel appareil connecté. Les contenus couvrent l'ensemble des domaines de compétences recherchés par les entreprises gabonaises : droit OHADA, comptabilité SYSCOHADA, gestion des ressources humaines selon le Code du Travail 2021, management de projet, compétences bureautiques avancées et langues professionnelles. Chaque module intègre des évaluations intermédiaires et une certification de fin de parcours.\n\nBien qu'il n'existe pas encore d'équivalent du CPF (Compte Personnel de Formation) ou du DIF français au Gabon, le financement des formations en ligne peut être imputé sur la Contribution à la Formation Professionnelle (CFP) de 0,50 % de la masse salariale brute (Art. 95-96 CGI). L'Arrêté n°0039/MEFPTFP/MESRSTTENFC du 21 avril 2021, qui régit les établissements de formation professionnelle, pose les bases d'une reconnaissance progressive des formats numériques dans le paysage de la formation au Gabon.\n\nOdillon développe ses plateformes e-learning en tenant compte des réalités du terrain gabonais : contenus optimisés pour les connexions à bande passante variable, sessions téléchargeables pour un apprentissage hors ligne, suivi individualisé par un tuteur dédié, et reporting complet à destination de la direction RH. Nous proposons également des formats hybrides combinant sessions en ligne et regroupements présentiels pour maximiser l'ancrage des apprentissages.",
            impact: "Accessibilité maximale et montée en compétences continue"
          },
          {
            title: "Formations courtes",
            content: "L'Arrêté n°0039/MEFPTFP/MESRSTTENFC du 21 avril 2021 régit les établissements de formation professionnelle au Gabon et encadre les différents formats de formation proposés aux entreprises et aux salariés. Les formations courtes, d'une durée de un à cinq jours, constituent un outil privilégié pour répondre à des besoins ciblés de montée en compétences sans mobiliser les collaborateurs sur de longues périodes. Elles s'inscrivent pleinement dans l'obligation de l'employeur de veiller au développement des compétences prévue par la Loi n°022/2021.\n\nNos formations courtes couvrent des thématiques opérationnelles précises : rédaction de contrats conformes au droit OHADA, tenue de la comptabilité selon le référentiel SYSCOHADA, gestion de la paie et des déclarations sociales (CNSS, CNAMGS), techniques de management d'équipe, conduite de réunions efficaces, ou encore maîtrise des outils numériques de gestion. Chaque session est construite autour d'objectifs pédagogiques mesurables et de mises en situation pratiques tirées du quotidien professionnel gabonais.\n\nLe Code du Travail 2021 prévoit que le salarié peut bénéficier d'un congé de formation selon les dispositions des conventions collectives sectorielles applicables. Ce congé permet au collaborateur de suivre la formation tout en conservant sa rémunération, les coûts étant imputables sur la CFP de 0,50 % de la masse salariale brute. L'employeur est tenu de faciliter l'accès à la formation et ne peut s'opposer au congé de formation sans motif légitime lié au fonctionnement de l'entreprise.\n\nOdillon organise des sessions de formations courtes en présentiel à Libreville, en intra-entreprise directement dans vos locaux, ou en format hybride combinant présentiel et distanciel. Nous prenons en charge l'ensemble du processus : analyse des besoins, conception du programme, sélection des formateurs spécialisés, logistique de la formation, évaluation des acquis et remise d'attestations de formation. Nos programmes sont régulièrement actualisés pour intégrer les dernières évolutions législatives et réglementaires.\n\nNe pas investir dans la formation courte expose l'entreprise à des risques concrets : obsolescence des compétences, non-conformité réglementaire, erreurs de procédure coûteuses et démotivation des équipes. A contrario, des collaborateurs régulièrement formés garantissent une meilleure productivité, une réduction des erreurs et une conformité continue avec le cadre légal en vigueur.",
            impact: "Application immédiate des acquis dans le respect du cadre réglementaire"
          }
        ]
      }
    ],
  legalReferences: [
    { title: "Code du Travail gabonais 2021", description: "Loi n°022/2021 - Obligations de formation", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/Code-Travail-Gabon-2021.pdf", type: "pdf" },
    { title: "Convention Collective Interprofessionnelle", description: "Congé de formation et obligations conventionnelles", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/Convention-Collective-Gabon.pdf", type: "pdf" },
    { title: "Code Général des Impôts (CGI 2025)", description: "Art. 95-96 - Contribution à la Formation Professionnelle (CFP 0,50%)", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/CGI-Gabon-2025.pdf", type: "pdf" },
    { title: "Sécurité sociale au Gabon", description: "Régime de protection sociale - CLEISS", url: "https://www.cleiss.fr/docs/regimes/regime_gabon.html", type: "link" }
  ]
  }
