import { ServiceData } from "./types"

export const juridiqueService: ServiceData = {
    id: "juridique",
    icon: "Scale",
    title: "Juridique",
    color: "#C4D82E",
    gradient: "from-[#C4D82E]/20 via-[#C4D82E]/10 to-transparent",
    tagline: "Accompagnement Juridique Externalisé",
    description: "Une expertise juridique couvrant l'intégralité du droit des affaires OHADA applicable au Gabon : droit commercial (AUDCG 2010), droit des sociétés (AUSCGIE 2014), sûretés (AUS 2010), arbitrage (AUA 2017) et procédures collectives (AUPCAP 2015).",
    keyBenefits: [
      { icon: "Shield", text: "Protection juridique", detail: "Tous vos contrats sécurisés" },
      { icon: "Scale", text: "Conformité assurée", detail: "Respect du droit OHADA et gabonais" },
      { icon: "Rocket", text: "Réactivité", detail: "Conseil disponible en temps réel" }
    ],
    workflow: [
      { step: "1", title: "Écoute", description: "Compréhension approfondie de vos enjeux et besoins juridiques", icon: "Search" },
      { step: "2", title: "Analyse", description: "Étude de votre situation et identification des risques juridiques", icon: "FileText" },
      { step: "3", title: "Action", description: "Rédaction, négociation et sécurisation de vos contrats", icon: "Scale" },
      { step: "4", title: "Veille", description: "Suivi réglementaire continu et mise en conformité", icon: "Shield" }
    ],
    services: [
      {
        icon: "FileText",
        name: "Service Juridique Externalisé",
        slug: "service-juridique-externalise",
        tagline: "Votre équipe juridique dédiée",
        description: "Une expertise juridique complète couvrant les 10 Actes Uniformes OHADA en vigueur et leur application en droit gabonais, sans les coûts d'une équipe interne.",
        details: [
          {
            title: "Service juridique externalisé",
            content: "Le droit des affaires applicable au Gabon repose sur un corpus juridique dense et en constante évolution, articulé autour de dix Actes Uniformes OHADA en vigueur et du droit national gabonais. Les principaux textes régissant la vie des entreprises sont l'Acte Uniforme relatif au Droit Commercial Général (AUDCG), adopté le 15 décembre 2010 et entré en vigueur le 15 mai 2011, qui encadre le statut de commerçant, le Registre du Commerce et du Crédit Mobilier (RCCM) et les baux commerciaux ; l'AUSCGIE révisé du 30 janvier 2014 relatif aux sociétés commerciales ; l'Acte Uniforme sur les Sûretés (AUS) révisé le 15 décembre 2010 ; l'Acte Uniforme relatif au Droit de l'Arbitrage (AUA) révisé le 23 novembre 2017 ; l'AUPCAP révisé le 10 septembre 2015 sur les procédures collectives ; et l'AUDCIF du 26 janvier 2017 sur la comptabilité. En l'absence de réglementation OHADA sur un sujet donné, le Code Civil gabonais et les lois nationales spéciales s'appliquent.\n\nUn service juridique externalisé assure une veille permanente sur l'ensemble de ces textes et leurs évolutions jurisprudentielles, tant au niveau de la Cour Commune de Justice et d'Arbitrage (CCJA) d'Abidjan que des juridictions nationales gabonaises. Cette veille est essentielle car le droit OHADA est un droit vivant, régulièrement enrichi par les avis de la CCJA et par les révisions périodiques des Actes Uniformes. Une entreprise qui n'actualise pas sa connaissance du cadre juridique s'expose à des risques de non-conformité, de contentieux évitables et d'opportunités manquées.\n\nPour de nombreuses entreprises gabonaises, en particulier les PME et les filiales de groupes internationaux, le recours à un service juridique externalisé offre un rapport qualité-coût supérieur à celui d'une équipe juridique interne permanente. L'externalisation permet d'accéder à une expertise pluridisciplinaire (droit commercial, droit des sociétés, droit social, droit fiscal, droit de l'arbitrage) sans supporter les charges fixes d'une direction juridique complète, tout en bénéficiant d'une réactivité et d'une disponibilité adaptées aux besoins réels de l'entreprise.\n\nOdillon met à votre disposition une équipe de juristes expérimentés maîtrisant l'ensemble du corpus OHADA et le droit gabonais des affaires. Nous assurons un accompagnement juridique permanent couvrant le conseil au quotidien, la veille réglementaire personnalisée, la rédaction et la révision de documents juridiques, l'assistance lors des opérations exceptionnelles et la gestion des précontentieux. Chaque client bénéficie d'un juriste référent qui connaît son activité, son secteur et ses enjeux spécifiques.",
            impact: "Sécurité juridique totale et conformité garantie au droit OHADA et gabonais"
          },
          {
            title: "Négociation des clauses financières des Contrats",
            content: "L'Acte Uniforme portant organisation des Sûretés (AUS), révisé le 15 décembre 2010, constitue le texte de référence en matière de garanties financières dans l'espace OHADA. Il organise un système complet de sûretés personnelles (cautionnement aux articles 13 à 38, garantie autonome et contre-garantie aux articles 39 à 49, lettre d'intention à l'article 50) et de sûretés réelles mobilières (gage, nantissement de créances, de compte bancaire, de droits de propriété intellectuelle, de valeurs mobilières) et immobilières (hypothèque conventionnelle, judiciaire et légale). L'AUDCG 2010 complète ce dispositif en encadrant les obligations de conformité et les garanties contractuelles dans les relations commerciales.\n\nLa négociation des clauses financières d'un contrat est un exercice technique qui requiert une maîtrise simultanée du droit des obligations, du droit des sûretés et des réalités économiques de la transaction. Les clauses clés à négocier incluent : les conditions et modalités de paiement (acompte, paiement échelonné, retenue de garantie), les pénalités de retard et clauses résolutoires, les sûretés exigées (cautionnement bancaire, garantie à première demande, nantissement de fonds de commerce, hypothèque), les clauses d'indexation et de révision des prix, les clauses de force majeure et d'imprévision, et les clauses de règlement des différends (juridiction compétente ou arbitrage OHADA).\n\nDans le contexte économique gabonais, la sécurisation des clauses financières revêt une importance particulière. Les délais de paiement, notamment dans les marchés publics, peuvent être significatifs. Le risque d'insolvabilité des partenaires commerciaux nécessite des mécanismes de protection adaptés. L'AUS 2010 a modernisé le droit des sûretés OHADA en introduisant de nouvelles formes de garanties (garantie autonome, nantissement de compte bancaire) et en simplifiant les formalités de constitution et de réalisation des sûretés, offrant ainsi aux entreprises des outils de protection plus efficaces.\n\nOdillon négocie vos clauses financières en mobilisant une expertise approfondie du droit OHADA des sûretés et des pratiques commerciales gabonaises. Nous analysons le profil de risque de chaque transaction, recommandons les mécanismes de garantie les plus adaptés, rédigeons les clauses financières dans un langage juridiquement précis et commercialement équilibré, et accompagnons les formalités de publication et d'inscription des sûretés au RCCM lorsque cela est requis par l'AUS 2010.",
            impact: "Protection maximale de vos intérêts dans chaque transaction"
          },
          {
            title: "Rédaction des contrats",
            content: "La rédaction de contrats dans l'espace OHADA mobilise simultanément plusieurs textes normatifs. L'AUDCG, adopté le 15 décembre 2010 et entré en vigueur le 15 mai 2011, constitue le socle du droit commercial général applicable aux contrats de vente commerciale, aux intermédiaires de commerce et aux baux commerciaux (articles 101 à 134). L'AUSCGIE révisé du 30 janvier 2014 encadre la rédaction des statuts sociaux selon la forme juridique choisie : SA (articles 385 à 853), SARL (articles 309 à 384), SAS (articles 853-1 à 853-23). L'AUA révisé le 23 novembre 2017 régit les clauses compromissoires et les conventions d'arbitrage. Le Code du Travail gabonais (Loi n°022/2021) encadre les contrats de travail. En l'absence de réglementation OHADA spécifique, le Code Civil gabonais s'applique au titre du droit commun des contrats.\n\nChaque type de contrat obéit à des exigences formelles et substantielles propres. Les statuts de société doivent contenir les mentions obligatoires prévues par l'AUSCGIE 2014 pour chaque forme juridique, sous peine de nullité. Les baux commerciaux (AUDCG, Art. 101-134) doivent respecter des durées minimales, des conditions de renouvellement et des règles de fixation et de révision du loyer spécifiques. Les contrats de travail gabonais doivent distinguer le CDI du CDD, respecter les dispositions relatives à la période d'essai, à la rémunération minimale, aux congés et au licenciement. Les clauses d'arbitrage OHADA doivent satisfaire aux conditions de validité de l'AUA 2017 pour être opposables.\n\nLa qualité de la rédaction contractuelle est un enjeu majeur pour les entreprises opérant au Gabon. Un contrat mal rédigé — qui omet une mention obligatoire, utilise une clause ambiguë ou ne prend pas en compte les spécificités du droit OHADA — expose l'entreprise à des risques de nullité, de contentieux coûteux et de perte financière. La jurisprudence de la Cour Commune de Justice et d'Arbitrage (CCJA) d'Abidjan sanctionne régulièrement les manquements aux formalités prescrites par les Actes Uniformes.\n\nOdillon rédige l'ensemble de vos contrats en maîtrisant le cadre juridique applicable. Pour chaque contrat, nous identifions les textes de référence (Actes Uniformes OHADA, droit gabonais, conventions internationales le cas échéant), intégrons les mentions obligatoires, rédigeons des clauses claires et protectrices de vos intérêts, prévoient les mécanismes de résolution des litiges les plus adaptés (juridiction étatique ou arbitrage OHADA) et veillons à la cohérence de l'ensemble contractuel. Nous assurons également la mise à jour de vos contrats types lors des évolutions législatives et réglementaires.",
            impact: "Contrats juridiquement sécurisés et adaptés au cadre légal en vigueur"
          },
          {
            title: "Analyse des contrats",
            content: "L'analyse contractuelle dans le cadre du droit OHADA est un exercice méthodique qui vise à identifier, évaluer et traiter l'ensemble des risques juridiques contenus dans un contrat avant tout engagement. Cette analyse mobilise le corpus complet des Actes Uniformes : l'AUDCG 2010 pour la validité des engagements commerciaux et le respect des obligations de conformité, l'AUSCGIE 2014 pour la vérification des pouvoirs du signataire et la conformité aux règles de gouvernance, l'AUS 2010 pour l'analyse des sûretés proposées ou exigées, l'AUA 2017 pour la validité et l'efficacité des clauses de règlement des litiges, et l'AUPCAP 2015 pour l'évaluation du risque d'insolvabilité du cocontractant.\n\nL'analyse porte sur plusieurs dimensions. La validité formelle vérifie le respect des conditions de forme prescrites par le droit applicable (mentions obligatoires, signatures, pouvoirs, enregistrement). La validité substantielle examine le consentement des parties (absence de vice : erreur, dol, violence), la capacité et les pouvoirs des signataires, la licéité et la détermination de l'objet, et l'existence d'une cause réelle et licite. L'analyse des clauses sensibles porte en particulier sur les clauses limitatives ou exonératoires de responsabilité, les clauses pénales, les clauses résolutoires, les clauses de non-concurrence, les clauses de confidentialité, les clauses de propriété intellectuelle et les clauses de droit applicable et de juridiction compétente.\n\nDans la pratique des affaires au Gabon, l'analyse contractuelle préalable est d'autant plus importante que les coûts d'un contentieux — en temps, en argent et en réputation — sont considérables. La procédure devant les tribunaux de commerce gabonais ou devant la CCJA d'Abidjan peut s'étendre sur plusieurs années. Les voies d'exécution, bien qu'encadrées par l'Acte Uniforme portant organisation des procédures simplifiées de recouvrement et des voies d'exécution (AUVE), restent parfois complexes à mettre en œuvre. Prévenir les litiges par une analyse contractuelle rigoureuse est toujours préférable à les gérer après leur survenance.\n\nOdillon réalise une analyse approfondie de vos contrats selon une grille méthodique couvrant l'ensemble des dimensions juridiques pertinentes. Nous produisons un rapport d'analyse structuré identifiant chaque point de risque, classé par niveau de criticité (élevé, moyen, faible), assorti de recommandations concrètes : clauses à modifier, clauses à ajouter, points à renégocier avec le cocontractant, sûretés complémentaires à exiger. Notre objectif est de vous permettre de signer des contrats en pleine connaissance des risques, avec des protections juridiques maximales.",
            impact: "Identification exhaustive des risques juridiques avant tout engagement"
          }
        ]
      }
    ],
  legalReferences: [
    { title: "AUSCGIE révisé 2014", description: "Droit des Sociétés Commerciales et du GIE", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/AUSCGIE-2014.pdf", type: "pdf" },
    { title: "AUDCG révisé 2010", description: "Acte Uniforme portant sur le Droit Commercial Général", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/AUDCG-2010.pdf", type: "pdf" },
    { title: "AUS révisé 2010", description: "Acte Uniforme portant organisation des Sûretés", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/AUS-2010.pdf", type: "pdf" },
    { title: "AUA 2017", description: "Acte Uniforme relatif au droit de l'Arbitrage", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/AUA-2017.pdf", type: "pdf" },
    { title: "Code du Travail gabonais 2021", description: "Loi n°022/2021 portant Code du Travail", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/Code-Travail-Gabon-2021.pdf", type: "pdf" },
    { title: "AUM 2017", description: "Acte Uniforme relatif à la Médiation", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/AUM-2017.pdf", type: "pdf" },
    { title: "Code des Marchés Publics", description: "Réglementation des marchés publics au Gabon", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/Code-Marches-Publics-Gabon.pdf", type: "pdf" },
    { title: "Règlement CEMAC Concurrence", description: "Règlement n°06/19 relatif à la concurrence dans la CEMAC", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/CEMAC-Concurrence-2019.pdf", type: "pdf" }
  ]
  }
