import { ServiceData } from "./types"

export const paieService: ServiceData = {
    id: "paie",
    icon: "Banknote",
    title: "Paie",
    color: "#C4D82E",
    gradient: "from-[#C4D82E]/20 via-[#C4D82E]/10 to-transparent",
    tagline: "Gestion de la Paie",
    description: "Externalisation complète de votre paie en conformité avec le Code du Travail gabonais (Loi n° 022/2021), les cotisations CNSS (23% depuis janvier 2026) et CNAMGS (6,1%), et le barème IRPP en vigueur.",
    keyBenefits: [
      { icon: "Shield", text: "Conformité garantie", detail: "Réglementation respectée" },
      { icon: "BarChart3", text: "Fiabilité", detail: "Bulletins sans erreur" },
      { icon: "Target", text: "Optimisation", detail: "Charges maîtrisées" }
    ],
    workflow: [
      { step: "1", title: "Audit", description: "Analyse de votre système de paie actuel et identification des besoins", icon: "Search" },
      { step: "2", title: "Configuration", description: "Mise en place et paramétrage du système de paie", icon: "Target" },
      { step: "3", title: "Production", description: "Traitement mensuel de la paie et des déclarations", icon: "FileText" },
      { step: "4", title: "Contrôle", description: "Vérification, reporting et amélioration continue", icon: "Shield" }
    ],
    services: [
      {
        icon: "FileText",
        name: "Externalisation de la Paie",
        slug: "externalisation-paie",
        tagline: "Confiez-nous votre paie",
        description: "Prise en charge complète de votre paie conformément au Code du Travail gabonais et aux obligations déclaratives CNSS, CNAMGS et DGI.",
        details: [
          {
            title: "Établissement des bulletins de paie",
            content: "Le bulletin de paie est un document juridique encadré par le Code du Travail gabonais (Loi n°022/2021) qui doit refléter avec exactitude l'ensemble des éléments de rémunération, des cotisations sociales et des retenues fiscales applicables au salarié. Sa production requiert une maîtrise technique pointue des différents régimes en vigueur, dont les paramètres ont été significativement modifiés par les réformes récentes, notamment le Décret n°0487/PR/MASI du 18 décembre 2025 portant réforme des taux CNSS.\n\nChaque bulletin que nous produisons intègre avec précision les cotisations CNSS au nouveau taux global de 23%, ventilé entre la part patronale de 18% (dont 5% pour l'assurance vieillesse, 5% pour les prestations familiales, environ 2% pour les accidents du travail et maladies professionnelles, et le reste en contributions complémentaires) et la part salariale de 5% (intégralement affectée à l'assurance vieillesse). Ces cotisations sont calculées sur le salaire brut plafonné à 1 500 000 FCFA par mois. S'y ajoutent les cotisations CNAMGS (assurance maladie) au taux de 6,1% total, soit 4,1% patronal et 2% salarial, sur un plafond de 2 500 000 FCFA par mois, conformément au Décret n°518/PR/MDSFPSSN du 22 décembre 2016.\n\nLa retenue à la source de l'Impôt sur le Revenu des Personnes Physiques (IRPP) est calculée selon le barème progressif en vigueur, dont les tranches s'échelonnent de 0% (revenus les plus faibles) à 35% (revenus les plus élevés). Nous appliquons les abattements et déductions légales (charges de famille, frais professionnels forfaitaires) pour déterminer le montant exact de la retenue. La Taxe Complémentaire sur les Salaires (TCS), à la charge de l'employeur, est également intégrée dans nos calculs.\n\nOdillon garantit la conformité de chaque bulletin au regard de l'ensemble des textes applicables. Nos contrôles systématiques vérifient le respect du SMIG (80 000 FCFA par mois, inchangé depuis 2006) et du Revenu Minimum Mensuel (RMM) de 150 000 FCFA net fixé par le Décret n°127/PR/MTEPS du 23 avril 2010, qui correspond au SMIG majoré des primes obligatoires prévues par les conventions collectives. Chaque élément variable (heures supplémentaires avec majorations conventionnelles, primes, indemnités, avantages en nature) est traité selon les règles fiscales et sociales qui lui sont propres.",
            impact: "Bulletins légalement conformes, zéro risque de redressement CNSS ou DGI"
          },
          {
            title: "Déclarations sociales et fiscales",
            content: "Les obligations déclaratives liées à la paie au Gabon sont multiples, avec des échéances distinctes auprès de trois organismes différents : la CNSS, la CNAMGS et la Direction Générale des Impôts (DGI). Le non-respect de ces échéances entraîne des pénalités de retard automatiques, des majorations pouvant atteindre 10% à 25% des sommes dues, et expose l'entreprise à des contrôles renforcés. Notre service garantit le respect scrupuleux de chaque échéance.\n\nLes Déclarations Trimestrielles des Salaires (DTS) constituent l'obligation principale envers la CNSS. Elles récapitulent pour chaque salarié l'ensemble des rémunérations soumises à cotisation sur le trimestre écoulé, dans la limite du plafond mensuel de 1 500 000 FCFA. La DTS doit être transmise au plus tard le 30 du mois suivant la fin du trimestre (soit le 30 avril pour le premier trimestre, le 31 juillet pour le deuxième, le 31 octobre pour le troisième, et le 31 janvier pour le quatrième). Depuis la réforme de décembre 2025, la première DTS aux nouveaux taux de 23% concerne les cotisations exigibles au 30 avril 2026. Nous préparons et transmettons ces déclarations en vérifiant la cohérence entre les bulletins de paie mensuels et les données trimestrielles consolidées.\n\nLes déclarations CNAMGS obéissent à un rythme mensuel. Chaque mois, l'employeur doit déclarer les rémunérations de ses salariés et verser les cotisations correspondantes au taux global de 6,1% (4,1% patronal + 2% salarial), calculées sur les salaires plafonnés à 2 500 000 FCFA par mois. Parallèlement, les retenues à la source d'IRPP et la Taxe Complémentaire sur les Salaires (TCS) doivent être déclarées et reversées à la DGI au plus tard le 20 du mois suivant celui du versement des salaires.\n\nOdillon met en place un calendrier déclaratif rigoureux qui anticipe chaque échéance. Nous préparons les déclarations en amont, les soumettons à votre validation, et assurons leur transmission dans les délais. En cas de contrôle de la CNSS, de la CNAMGS ou de l'administration fiscale, nous vous accompagnons dans la préparation des justificatifs et la réponse aux demandes d'information. Notre veille permanente sur les évolutions réglementaires garantit que vos déclarations intègrent toujours les derniers paramètres en vigueur.",
            impact: "Conformité totale avec les obligations déclaratives gabonaises"
          },
          {
            title: "Gestion des entrées et sorties",
            content: "Le cycle de vie d'un contrat de travail au Gabon est encadré par le Code du Travail (Loi n°022/2021), qui définit des règles précises pour chaque étape : embauche, exécution, modification et rupture. Le non-respect de ces dispositions expose l'employeur à des litiges prud'homaux coûteux et à des sanctions administratives. Notre service couvre l'intégralité de ce cycle avec une rigueur juridique qui protège votre entreprise.\n\nÀ l'entrée, nous établissons les contrats de travail conformes aux prescriptions légales. Le Contrat à Durée Indéterminée (CDI) est la forme de droit commun. Le Contrat à Durée Déterminée (CDD) est encadré par l'article 23 du Code du Travail qui limite sa durée à deux ans maximum, renouvellement inclus. Tout CDD dépassant cette durée est automatiquement requalifié en CDI, avec les conséquences juridiques et financières que cela implique. Nous paramétrons les périodes d'essai conformément à l'article 49 : un mois maximum pour les employés et ouvriers, trois mois pour les techniciens et agents de maîtrise, et six mois pour les cadres, chaque période étant renouvelable une fois dans les mêmes limites. La déclaration du salarié auprès de la CNSS et de la CNAMGS est effectuée dans les délais réglementaires.\n\nÀ la sortie, le calcul du solde de tout compte requiert une attention particulière pour éviter tout contentieux. L'indemnité de licenciement, prévue par le Code du Travail, est calculée sur la base de 20% du salaire moyen des douze derniers mois de service par année d'ancienneté dans l'entreprise. Les préavis légaux varient selon l'ancienneté et la catégorie professionnelle du salarié : de quinze jours pour les salariés ayant moins d'un an d'ancienneté, à un mois pour ceux ayant entre un et trois ans, jusqu'à six mois ou plus pour les cadres supérieurs de longue ancienneté, selon les dispositions des conventions collectives applicables. En cas de licenciement pour motif économique, des procédures spécifiques de consultation et de notification à l'Inspection du Travail doivent être respectées.\n\nOdillon traite chaque départ avec une méthodologie rigoureuse : calcul exhaustif de tous les éléments dus (indemnité de licenciement, indemnité compensatrice de préavis, indemnité compensatrice de congés payés, prorata de gratification, remboursement de frais), établissement du certificat de travail et du reçu pour solde de tout compte, radiation auprès des organismes sociaux, et archivage du dossier. Nous veillons à ce que chaque élément soit conforme aux dispositions légales et conventionnelles, minimisant ainsi le risque de contestation ultérieure devant le Tribunal du Travail.",
            impact: "Sécurité juridique totale à chaque étape du cycle de vie du contrat"
          },
          {
            title: "Veille réglementaire paie",
            content: "L'environnement réglementaire de la paie au Gabon évolue régulièrement, comme en témoigne la réforme majeure des taux CNSS intervenue en décembre 2025. Le Décret n°0487/PR/MASI du 18 décembre 2025 a porté le taux global de cotisation CNSS de l'ancien barème à 23% (18% patronal + 5% salarial), avec un nouveau plafond de 1 500 000 FCFA par mois. Cette réforme, dont la première échéance de cotisation aux nouveaux taux est fixée au 30 avril 2026, a un impact direct sur le coût du travail et nécessite une adaptation immédiate des paramètres de paie. Sans veille proactive, les entreprises s'exposent à des sous-cotisations génératrices de redressements ou à des sur-cotisations qui grèvent inutilement leur trésorerie.\n\nNotre service de veille couvre l'ensemble des textes susceptibles d'affecter la paie. Nous suivons en permanence les évolutions du SMIG (maintenu à 80 000 FCFA par mois depuis 2006, mais régulièrement évoqué dans les discussions tripartites gouvernement-patronat-syndicats) et du Revenu Minimum Mensuel (RMM de 150 000 FCFA net, fixé par le Décret n°127/PR/MTEPS du 23 avril 2010, qui inclut le SMIG majoré des primes obligatoires). Nous surveillons également les modifications du barème progressif de l'IRPP, les ajustements de la TCS, et toute évolution des taux CNAMGS.\n\nAu-delà des textes nationaux, notre veille englobe les conventions collectives sectorielles qui complètent le Code du Travail en matière de grilles salariales, de classifications professionnelles, de majorations pour heures supplémentaires et de primes spécifiques à chaque branche d'activité. Les Lois de Finances annuelles font également l'objet d'une analyse systématique, car elles peuvent modifier les taux d'imposition, introduire de nouvelles taxes ou ajuster les seuils d'exonération.\n\nOdillon traduit chaque évolution réglementaire en action concrète pour votre paie. Dès la publication d'un nouveau texte, nous en analysons l'impact sur vos bulletins de salaire, mettons à jour les paramètres de calcul, informons votre direction des conséquences financières et, le cas échéant, procédons aux régularisations nécessaires. Ce service proactif vous garantit une conformité permanente sans que vous ayez à mobiliser vos propres ressources pour assurer cette surveillance réglementaire.",
            impact: "Anticipation des réformes sociales et adaptation instantanée de la paie"
          }
        ]
      },
      {
        icon: "BarChart3",
        name: "Conseil et Optimisation Paie",
        slug: "conseil-optimisation-paie",
        tagline: "Optimisez vos coûts salariaux",
        description: "Audit, optimisation et pilotage de votre masse salariale dans le strict respect de la réglementation gabonaise.",
        details: [
          {
            title: "Audit de paie",
            content: "L'audit de paie est un examen méthodique et exhaustif de l'ensemble de votre processus de rémunération, destiné à vérifier sa conformité avec les textes législatifs et réglementaires en vigueur au Gabon. Face à la complexité croissante de la réglementation sociale et fiscale, et aux réformes fréquentes (comme la révision des taux CNSS par le Décret n°0487/PR/MASI du 18 décembre 2025), un audit régulier est indispensable pour sécuriser votre passif social et prévenir les risques de redressement.\n\nNotre audit couvre point par point chaque composante de la paie. Nous vérifions l'application correcte des taux de cotisation CNSS à 23% (18% patronal décomposé en 5% assurance vieillesse, 5% prestations familiales, environ 2% AT/MP et contributions complémentaires, et 5% salarial entièrement affecté à la vieillesse), avec un plafond de 1 500 000 FCFA par mois. Nous contrôlons les cotisations CNAMGS au taux de 6,1% (4,1% patronal + 2% salarial) sur un plafond de 2 500 000 FCFA par mois. Le calcul de l'IRPP retenu à la source est vérifié tranche par tranche selon le barème progressif (de 0% à 35%), en tenant compte des abattements légaux et des situations familiales des salariés.\n\nNous contrôlons également le respect des minimums légaux : SMIG de 80 000 FCFA par mois (inchangé depuis 2006) et Revenu Minimum Mensuel (RMM) de 150 000 FCFA net fixé par le Décret n°127/PR/MTEPS du 23 avril 2010. Le RMM, souvent méconnu, inclut le SMIG majoré des primes obligatoires prévues par les conventions collectives (prime de transport, prime d'ancienneté, indemnité de logement selon les secteurs). Son non-respect constitue une infraction au droit du travail. Notre audit examine aussi la correcte application des majorations pour heures supplémentaires, le calcul des congés payés (minimum 24 jours ouvrables par an), et le traitement des avantages en nature.\n\nÀ l'issue de l'audit, nous remettons un rapport détaillé identifiant les écarts constatés, leur nature (sur-cotisation ou sous-cotisation), leur montant financier, et le risque juridique associé. Chaque écart est accompagné d'une recommandation de régularisation chiffrée. En cas de sur-cotisations identifiées (CNSS ou CNAMGS), nous assistons l'entreprise dans les démarches de récupération auprès des organismes concernés. En cas de sous-cotisations, nous procédons aux régularisations avant qu'un contrôle ne les détecte, transformant ainsi un risque de redressement en mise en conformité volontaire.",
            impact: "Sécurisation du passif social et identification des risques de redressement"
          },
          {
            title: "Optimisation des charges sociales",
            content: "L'optimisation des charges sociales est un levier stratégique majeur pour la compétitivité de votre entreprise au Gabon. Avec un taux de cotisation patronale CNSS de 18% et un taux CNAMGS de 4,1%, auxquels s'ajoutent la TCS et les autres contributions, le coût total employeur représente un pourcentage significatif de la masse salariale brute. Notre approche d'optimisation vise à réduire ce coût de manière strictement légale, en exploitant les mécanismes prévus par le Code du Travail (Loi n°022/2021), le Code Général des Impôts gabonais et les conventions collectives applicables.\n\nLa première dimension de l'optimisation porte sur la structure de rémunération. Certaines indemnités et allocations ne sont pas soumises aux cotisations CNSS et CNAMGS lorsqu'elles répondent à des conditions précises : remboursements de frais professionnels sur justificatifs, indemnités de déplacement dans les limites réglementaires, allocations forfaitaires pour utilisation du véhicule personnel à des fins professionnelles. En restructurant la politique de rémunération pour distinguer clairement le salaire de base des éléments accessoires légalement exonérés, il est possible de réduire l'assiette de cotisation sans diminuer le revenu global perçu par le salarié.\n\nL'effet de plafonnement constitue un deuxième levier d'optimisation. Les cotisations CNSS étant plafonnées à 1 500 000 FCFA par mois et les cotisations CNAMGS à 2 500 000 FCFA par mois, toute rémunération au-delà de ces seuils n'est pas soumise aux cotisations correspondantes. Pour les cadres supérieurs dont la rémunération dépasse ces plafonds, l'arbitrage entre augmentation salariale et autres formes de rétribution (intéressement, avantages sociaux complémentaires) peut être financièrement optimisé.\n\nOdillon réalise une analyse complète de votre masse salariale pour identifier tous les leviers d'optimisation exploitables dans le strict respect de la législation. Nous établissons des simulations chiffrées comparant différents scénarios de structuration de la rémunération et quantifions les économies réalisables. Chaque recommandation est documentée par les textes juridiques qui la fondent, garantissant une sécurité totale en cas de contrôle. Notre objectif est de vous permettre d'offrir une rémunération attractive à vos collaborateurs tout en maîtrisant votre coût total employeur.",
            impact: "Réduction maîtrisée et légale des charges sociales patronales"
          },
          {
            title: "Tableaux de bord sociaux",
            content: "Le pilotage de la masse salariale nécessite des outils de reporting adaptés au contexte réglementaire gabonais. Le coût total employeur ne se limite pas au salaire brut : il inclut les cotisations patronales CNSS (18% du salaire brut plafonné à 1 500 000 FCFA/mois), les cotisations patronales CNAMGS (4,1% du salaire brut plafonné à 2 500 000 FCFA/mois), la Taxe Complémentaire sur les Salaires, les contributions à la formation professionnelle et les charges sociales complémentaires éventuelles. Sans tableaux de bord précis, de nombreuses entreprises sous-estiment leur coût réel du travail et prennent des décisions de recrutement ou d'augmentation mal calibrées.\n\nNos tableaux de bord sociaux couvrent l'ensemble des indicateurs clés de gestion des ressources humaines : évolution mensuelle et annuelle de la masse salariale brute et nette, coût total employeur par salarié et par département, ratio charges sociales / masse salariale, suivi du taux de turnover (entrées et sorties par période), taux d'absentéisme ventilé par motif (maladie, accidents du travail, absences injustifiées), volume et coût des heures supplémentaires avec les majorations conventionnelles applicables, et solde de congés payés par salarié (le minimum légal étant de 24 jours ouvrables par an au Gabon).\n\nUn volet essentiel de notre reporting concerne le suivi des échéances déclaratives. Le calendrier social gabonais est jalonné d'échéances strictes dont le non-respect entraîne des pénalités : DTS trimestrielles CNSS (30 du mois suivant la fin du trimestre), déclarations mensuelles CNAMGS, reversement IRPP et TCS (20 du mois suivant), déclaration annuelle des salaires à la DGI, et attestations annuelles individuelles. Notre tableau de bord intègre un système d'alerte anticipée qui vous prévient suffisamment en amont pour préparer chaque déclaration sereinement.\n\nOdillon conçoit ces tableaux de bord sur mesure en fonction de la taille, du secteur et des besoins spécifiques de votre entreprise. Les données sont présentées sous forme de graphiques et de tableaux synthétiques permettant une lecture rapide par la direction générale et la direction financière. Des analyses comparatives d'un exercice sur l'autre mettent en évidence les tendances et les points d'attention. Ces outils deviennent de véritables instruments de pilotage stratégique qui éclairent vos décisions en matière de politique salariale, de recrutement et d'organisation du travail.",
            impact: "Pilotage éclairé de la masse salariale et anticipation des échéances"
          }
        ]
      }
    ],
  legalReferences: [
    { title: "Code du Travail gabonais 2021", description: "Loi n°022/2021 - Rémunération et contrats", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/Code-Travail-Gabon-2021.pdf", type: "pdf" },
    { title: "Code de protection sociale", description: "Loi n°28/2016 - Branches de sécurité sociale", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/Code-Protection-Sociale-Gabon-2017.pdf", type: "pdf" },
    { title: "Convention Collective Interprofessionnelle", description: "Grilles salariales, classifications et primes obligatoires", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/Convention-Collective-Gabon.pdf", type: "pdf" },
    { title: "Code Général des Impôts (CGI 2025)", description: "Barème IRPP, TCS et contributions salariales", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/CGI-Gabon-2025.pdf", type: "pdf" },
    { title: "Cotisations sociales au Gabon", description: "Taux CNSS et CNAMGS en vigueur - CLEISS", url: "https://www.cleiss.fr/docs/cotisations/gabon.html", type: "link" },
    { title: "CNSS - Réforme 2026", description: "Décret n°0487/PR/MASI - Nouveaux taux", url: "https://www.cleiss.fr/docs/regimes/regime_gabon.html", type: "link" }
  ]
  }
