import { ServiceData } from "./types"

export const ressourcesHumainesService: ServiceData = {
    id: "ressources-humaines",
    icon: "Users",
    title: "Capital Humain",
    color: "#C4D82E",
    gradient: "from-[#C4D82E]/20 via-[#C4D82E]/10 to-transparent",
    tagline: "Administration et Ressources Humaines",
    description: "Gestion stratégique de votre capital humain en conformité avec le Code du Travail gabonais (Loi n° 022/2021) et les obligations sociales (CNSS, CNAMGS). De la politique RH au développement des compétences.",
    keyBenefits: [
      { icon: "Users2", text: "Talents retenus", detail: "Turnover réduit" },
      { icon: "Award", text: "Performance accrue", detail: "Engagement renforcé" },
      { icon: "Rocket", text: "Culture d'excellence", detail: "Organisation apprenante" }
    ],
    workflow: [
      { step: "1", title: "Audit", description: "État des lieux complet de votre capital humain et de vos pratiques RH", icon: "Search" },
      { step: "2", title: "Stratégie", description: "Définition des politiques RH alignées avec votre vision d'entreprise", icon: "Target" },
      { step: "3", title: "Déploiement", description: "Mise en œuvre des plans d'action et des programmes de développement", icon: "Rocket" },
      { step: "4", title: "Évaluation", description: "Mesure de la performance et ajustement continu des dispositifs", icon: "Award" }
    ],
    services: [
      {
        icon: "Target",
        name: "Projets et Chartes d'Entreprise",
        slug: "projets-chartes-entreprise",
        tagline: "Alignez votre capital humain",
        description: "Définissez le cadre stratégique et opérationnel de vos ressources humaines en conformité avec le Code du Travail gabonais (Loi n° 022/2021).",
        details: [
          {
            title: "Identification des atouts et des handicaps de l'Entreprise",
            content: "Le Code du Travail gabonais (Loi n°022/2021 du 19 novembre 2021), composé de 413 articles répartis en 8 titres, constitue le cadre de référence pour l'ensemble des relations de travail au Gabon. Il remplace l'ancienne Loi n°3/94 et renforce significativement les obligations de l'employeur en matière de gestion du capital humain. Tout diagnostic RH sérieux doit partir d'une analyse exhaustive de la conformité de l'entreprise à ce nouveau texte.\n\nNotre audit couvre l'intégralité des dimensions de votre organisation humaine. Sur le plan contractuel, nous vérifions que le CDI est bien utilisé comme forme normale du contrat de travail et que le recours au CDD respecte la limitation à 2 ans maximum (Art. 23). Sur le plan des instances représentatives, nous contrôlons la mise en place des délégués du personnel (obligatoires dès 11 salariés) et du Comité de Santé, Sécurité et Conditions de Travail (CSST, obligatoire dès 50 salariés). Sur le plan social, nous auditons la conformité des déclarations et cotisations CNSS (23 % dont 18 % part patronale et 5 % part salariale, plafond de 1 500 000 FCFA/mois depuis la réforme du Décret n°0487/PR/MASI du 18 décembre 2025) et CNAMGS (6,1 % dont 4,1 % part patronale et 2 % part salariale, plafond de 2 500 000 FCFA/mois).\n\nL'audit débouche sur une cartographie précise des risques juridiques et sociaux : contrats non conformes, instances manquantes, cotisations mal calculées, conventions collectives non appliquées. Chaque écart identifié est assorti d'une recommandation corrective priorisée par niveau de risque.\n\nOdillon produit un rapport d'audit détaillé qui constitue le point de départ de toute stratégie RH structurée. Ce diagnostic permet à la direction de prendre des décisions éclairées et de sécuriser juridiquement l'entreprise face aux contrôles de l'Inspection du Travail et de la CNSS.",
            impact: "Vision claire des enjeux et identification des risques de non-conformité"
          },
          {
            title: "Définition des objectifs et des plans d'action",
            content: "La feuille de route RH doit conjuguer la vision stratégique de l'entreprise avec les obligations impératives du Code du Travail gabonais (Loi n°022/2021). Parmi les contraintes légales structurantes figurent la durée légale du travail fixée à 40 heures par semaine réparties sur 5 jours (Décret n°0028/2021), les congés payés de 2 jours ouvrables par mois de service effectif soit 24 jours par an minimum (Art. 222 à 225), et le respect des conventions collectives sectorielles applicables à votre branche d'activité.\n\nNos consultants élaborent avec votre direction un plan d'action RH structuré en axes prioritaires : conformité juridique (mise en règle des contrats, des instances représentatives et des déclarations sociales), développement organisationnel (organigramme, fiches de poste, processus de recrutement), politique de rémunération (respect du SMIG de 80 000 FCFA et du Revenu Minimum Mensuel de 150 000 FCFA fixé par le Décret n°127/PR/MTEPS du 23 avril 2010), et gestion prévisionnelle des emplois et des compétences.\n\nChaque objectif est assorti d'indicateurs de suivi mesurables, d'un calendrier de mise en oeuvre et d'un responsable identifié. Le plan intègre également les échéances légales récurrentes : renouvellement des mandats de délégués du personnel, bilans sociaux, déclarations trimestrielles CNSS et déclarations mensuelles CNAMGS et IRPP.\n\nOdillon assure le pilotage du plan d'action avec des points d'avancement réguliers et des ajustements en fonction des évolutions législatives. Au Gabon, où il n'existe pas de convention collective nationale unique mais des conventions sectorielles, notre expertise permet de naviguer dans la complexité réglementaire propre à chaque secteur d'activité.",
            impact: "Cohérence organisationnelle et conformité légale totale"
          },
          {
            title: "Mise en place des indicateurs de performance",
            content: "La mesure de la performance RH est indispensable pour piloter efficacement le capital humain et anticiper les risques juridiques et financiers. Au Gabon, les cotisations sociales représentent un coût significatif pour l'employeur : depuis la réforme de janvier 2026 (Décret n°0487/PR/MASI du 18 décembre 2025), les cotisations CNSS s'élèvent à 23 % du salaire brut plafonné (18 % part patronale, 5 % part salariale) sur un plafond mensuel de 1 500 000 FCFA, auxquelles s'ajoutent les cotisations CNAMGS de 6,1 % (4,1 % patronale, 2 % salariale) sur un plafond de 2 500 000 FCFA.\n\nNos tableaux de bord RH couvrent l'ensemble des dimensions clés : masse salariale brute et chargée (incluant le coût total employeur avec cotisations patronales), taux de turnover global et par département, taux d'absentéisme, délai moyen de recrutement, taux de couverture des postes critiques, ratio d'encadrement, et indice de satisfaction des collaborateurs. Chaque indicateur est contextualisé par rapport aux moyennes sectorielles gabonaises lorsque les données sont disponibles.\n\nUn volet spécifique est consacré au suivi de la conformité réglementaire : respect des délais de déclaration CNSS (trimestrielle), CNAMGS (mensuelle) et IRPP (mensuelle), taux de conformité des contrats de travail, présence effective des instances représentatives du personnel, et suivi des formations obligatoires en matière de santé et sécurité au travail.\n\nOdillon paramètre ces indicateurs dans vos outils de gestion et forme vos responsables RH à leur interprétation. Un reporting mensuel synthétique est produit pour la direction générale, permettant de détecter rapidement les dérives et de prendre les mesures correctives avant qu'elles ne se transforment en contentieux ou en redressement social.",
            impact: "Pilotage RH basé sur des données fiables et actualisées"
          },
          {
            title: "Analyse des systèmes d'information du Capital Humain",
            content: "Un Système d'Information des Ressources Humaines (SIRH) performant est devenu indispensable pour gérer la complexité croissante des obligations sociales et fiscales au Gabon. La multiplicité des régimes de cotisation (CNSS trimestrielle, CNAMGS mensuelle, IRPP mensuel), les plafonds différenciés (1 500 000 FCFA pour la CNSS, 2 500 000 FCFA pour la CNAMGS) et les taux spécifiques à chaque régime rendent le traitement manuel source d'erreurs coûteuses lors des contrôles.\n\nNotre analyse porte sur l'ensemble de la chaîne de gestion RH informatisée : module de gestion administrative (contrats, avenants, dossiers du personnel), module de gestion des temps et des absences (suivi des 24 jours de congés annuels minimum, majoration d'ancienneté après 5 ans, congés exceptionnels prévus par le Code du Travail), module de paie (calcul du brut au net avec application automatique des barèmes CNSS, CNAMGS et IRPP), et module de reporting réglementaire (états récapitulatifs pour les organismes sociaux).\n\nNous évaluons la capacité de votre SIRH actuel à prendre en charge les spécificités gabonaises : gestion des conventions collectives sectorielles (chaque secteur ayant ses propres grilles et primes), calcul des indemnités légales (licenciement, fin de contrat, départ à la retraite), suivi des périodes d'essai différenciées selon les catégories (6 mois pour les cadres, 3 mois pour les techniciens, 1 mois pour les employés selon l'Art. 49), et production des documents obligatoires (bulletins de paie, certificats de travail, attestations).\n\nOdillon vous accompagne dans le choix, le paramétrage ou l'optimisation de votre SIRH, en veillant à ce qu'il intègre les dernières évolutions réglementaires, notamment la réforme des cotisations CNSS entrée en vigueur en janvier 2026. Nous assurons la migration des données, la formation des utilisateurs et le support post-déploiement.",
            impact: "Processus RH digitalisés et erreurs de gestion éliminées"
          }
        ]
      },
      {
        icon: "Users2",
        name: "Politiques de Développement du Capital Humain",
        slug: "developpement-capital-humain",
        tagline: "Cultivez l'excellence",
        description: "Développez et optimisez votre capital humain conformément aux obligations de formation et de développement des compétences prévues par le Code du Travail gabonais (Loi n° 022/2021).",
        details: [
          {
            title: "Management de la mauvaise performance",
            content: "Le Code du Travail gabonais (Loi n°022/2021) encadre strictement la gestion disciplinaire et les procédures de licenciement. La loi distingue trois niveaux de faute : la faute simple (pouvant entraîner un avertissement ou un blâme), la faute grave (justifiant un licenciement avec préavis) et la faute lourde (autorisant un licenciement immédiat sans préavis ni indemnité). L'employeur doit dans tous les cas respecter une procédure contradictoire comprenant un entretien préalable suivi d'un délai de réflexion de 5 jours ouvrables avant toute notification de sanction.\n\nAvant d'en arriver aux mesures disciplinaires, Odillon vous aide à mettre en place un dispositif structuré de gestion de la sous-performance. Ce dispositif comprend la détection précoce des écarts de performance (via les entretiens d'évaluation et les indicateurs de suivi), l'élaboration de plans d'amélioration individuels (PIP - Performance Improvement Plan) avec des objectifs SMART et un calendrier défini, et un accompagnement managérial renforcé (coaching, formation ciblée, mentorat).\n\nLorsque la procédure disciplinaire devient nécessaire, nous veillons au respect scrupuleux de chaque étape légale pour sécuriser juridiquement l'entreprise : convocation écrite à l'entretien préalable, tenue de l'entretien en présence d'un représentant du personnel si le salarié le souhaite, respect du délai de 5 jours, notification motivée de la sanction. En cas de licenciement, les durées de préavis varient de 15 jours à plus de 6 mois selon l'ancienneté du salarié, et l'indemnité de licenciement est fixée à 20 % du salaire mensuel moyen par année d'ancienneté (minimum 2 ans d'ancienneté requis).\n\nNotre approche privilégie systématiquement la prévention et la correction avant la sanction, mais garantit que chaque décision est juridiquement inattaquable en cas de contentieux devant le Tribunal du Travail.",
            impact: "Performance améliorée dans un cadre juridiquement sécurisé"
          },
          {
            title: "Transformation qualitative du Capital Humain",
            content: "Le Code du Travail gabonais (Loi n°022/2021) impose à l'employeur une obligation de veiller au maintien et au développement des compétences de ses salariés tout au long de la relation de travail. Cette obligation, renforcée par rapport à l'ancienne Loi n°3/94, s'inscrit dans un contexte de transformation rapide des métiers et des technologies qui touche l'ensemble des secteurs économiques du Gabon.\n\nConcrètement, cette obligation se traduit par la nécessité de mettre en place des programmes de formation adaptés aux évolutions du poste de travail, de faciliter l'accès à la formation professionnelle continue, et de garantir l'égalité d'accès entre hommes et femmes conformément au principe d'égalité de traitement consacré par le Code du Travail 2021. L'employeur qui néglige cette obligation s'expose à des difficultés en cas de licenciement pour insuffisance professionnelle, le juge pouvant considérer qu'il a manqué à son devoir d'adaptation.\n\nOdillon conçoit des programmes de transformation des compétences sur mesure, articulés autour de trois axes : la montée en compétences techniques (digitalisation, nouvelles normes sectorielles, évolutions réglementaires OHADA et CEMAC), le développement des compétences managériales (leadership, gestion d'équipe, conduite du changement), et le renforcement des compétences transversales (communication, gestion de projet, langues). Chaque programme est construit à partir d'un diagnostic des écarts entre les compétences actuelles et les compétences requises.\n\nNos interventions s'appuient sur les conventions collectives sectorielles qui, au Gabon, prévoient souvent des dispositions spécifiques en matière de formation. Nous mobilisons les dispositifs de financement disponibles et produisons les rapports nécessaires pour justifier de la conformité de l'entreprise à ses obligations légales de développement des compétences.",
            impact: "Montée en compétences conforme aux obligations légales de l'employeur"
          },
          {
            title: "Gestion des Talents",
            content: "La gestion des talents au Gabon s'inscrit dans un cadre juridique précis défini par le Code du Travail (Loi n°022/2021). Le CDI constitue la forme normale du contrat de travail, tandis que le CDD est limité à 2 ans maximum renouvellements compris (Art. 23). Les périodes d'essai sont encadrées par l'article 49 : 6 mois maximum pour les cadres, 3 mois pour les agents de maîtrise et techniciens, et 1 mois pour les employés et ouvriers. Ces dispositions structurent directement la politique de recrutement et d'intégration des talents.\n\nNotre approche de la gestion des talents couvre l'intégralité du cycle de vie du collaborateur, depuis l'identification des besoins jusqu'à la fidélisation des hauts potentiels. Nous mettons en place des processus de recrutement conformes aux exigences légales (non-discrimination, égalité d'accès hommes-femmes) et des parcours d'intégration structurés qui exploitent pleinement les périodes d'essai pour valider l'adéquation poste-profil dans les délais légaux.\n\nPour les talents identifiés comme hauts potentiels, nous concevons des programmes de développement accéléré combinant formation, mentorat par des dirigeants expérimentés, missions transversales et exposition à des projets stratégiques. Ces programmes tiennent compte du contexte gabonais où la rareté de certains profils qualifiés rend la rétention des talents d'autant plus critique pour la compétitivité de l'entreprise.\n\nOdillon vous aide également à construire un « vivier de talents » en anticipant les besoins futurs de l'organisation. Nous élaborons des plans de succession pour les postes clés et veillons à ce que chaque mouvement de personnel (promotion, mobilité interne, départ) soit géré dans le respect des dispositions contractuelles et conventionnelles en vigueur.",
            impact: "Pipeline de leaders assuré avec des contrats conformes"
          },
          {
            title: "Remodelage des carrières",
            content: "Le remodelage des parcours professionnels est un levier stratégique de fidélisation et d'optimisation du capital humain. Au Gabon, les mouvements de personnel sont encadrés par des dispositions légales précises : les durées de préavis varient de 15 jours pour les salariés ayant moins d'un an d'ancienneté à plus de 6 mois pour les cadres supérieurs ayant une longue ancienneté, et l'indemnité de licenciement est calculée à hauteur de 20 % du salaire mensuel moyen par année d'ancienneté (avec un minimum de 2 ans d'ancienneté requis pour en bénéficier).\n\nNotre démarche de remodelage des carrières part d'une cartographie complète des parcours existants au sein de votre organisation : filières d'évolution, passerelles entre métiers, critères de promotion et niveaux de classification selon la convention collective applicable. Nous identifions les parcours types, les impasses de carrière et les opportunités de mobilité interne qui permettent de retenir les talents tout en répondant aux besoins évolutifs de l'entreprise.\n\nPour les postes stratégiques, nous élaborons des plans de succession formalisés qui anticipent les départs prévisibles (retraite, fin de contrat, mobilité) et organisent la transmission progressive des compétences critiques. En cas de licenciement économique, le Code du Travail (Loi n°022/2021) impose l'obtention d'une autorisation de l'Inspecteur du Travail et le respect d'un délai de 30 jours, rendant indispensable une anticipation rigoureuse des restructurations.\n\nOdillon accompagne chaque collaborateur concerné dans la transition, en proposant des bilans de compétences, des formations de reconversion et un appui à la mobilité interne. Cette approche humaine et structurée préserve le climat social de l'entreprise tout en garantissant le respect de toutes les obligations légales attachées à chaque mouvement de personnel.",
            impact: "Rétention des talents clés et transitions maîtrisées"
          },
          {
            title: "Mise en place et suivi du Plan individuel de développement",
            content: "Le plan individuel de développement (PID) est un outil de gestion personnalisé qui formalise les objectifs de progression d'un collaborateur et les moyens mis en oeuvre pour les atteindre. Si la Gestion Prévisionnelle des Emplois et des Compétences (GPEC) n'est pas une obligation légale formelle au Gabon, contrairement à la France ou à d'autres juridictions, elle constitue néanmoins une bonne pratique de gestion avancée que nous recommandons vivement aux entreprises soucieuses de pérenniser leur capital humain.\n\nChaque PID est construit à partir de l'évaluation des compétences actuelles du collaborateur, rapportée aux exigences de son poste et aux perspectives d'évolution identifiées dans le plan de carrière. Le programme peut inclure des formations internes ou externes, du coaching individuel, des missions d'immersion dans d'autres services, ou encore un mentorat par un cadre expérimenté. Le salarié peut également bénéficier d'un congé de formation selon les dispositions prévues par la convention collective sectorielle applicable.\n\nLe suivi du PID fait l'objet de points d'étape trimestriels entre le collaborateur, son manager et le service RH. Chaque étape est documentée, les progrès sont mesurés par rapport aux objectifs fixés, et des ajustements sont apportés en fonction des résultats obtenus et des évolutions du contexte professionnel. Ce suivi rigoureux garantit l'efficacité de l'investissement formation et permet de mesurer le retour sur investissement pour l'entreprise.\n\nOdillon conçoit et pilote l'ensemble du dispositif PID pour votre organisation, de la méthodologie d'évaluation initiale jusqu'au reporting de synthèse. Nous formons vos managers à la conduite des entretiens de développement et instaurons une culture d'organisation apprenante où chaque collaborateur est acteur de sa propre progression professionnelle.",
            impact: "Organisation apprenante et collaborateurs engagés dans leur développement"
          }
        ]
      },
      {
        icon: "Award",
        name: "Politiques d'Évaluation de la Performance des Employés",
        slug: "evaluation-performance",
        tagline: "Mesurez et reconnaissez",
        description: "Systèmes d'évaluation objectifs et programmes de reconnaissance, fondés sur des critères non discriminatoires conformément aux principes du Code du Travail gabonais.",
        details: [
          {
            title: "Mise en place du système d'appréciation et d'évaluation",
            content: "Le Code du Travail gabonais (Loi n°022/2021) consacre le principe de non-discrimination dans toutes les dimensions de la relation de travail, y compris l'évaluation des performances. Les critères d'appréciation doivent être objectifs, mesurables et appliqués sans distinction d'origine, d'opinion politique ou religieuse, de sexe ou d'âge. Tout système d'évaluation discriminatoire expose l'employeur à des sanctions et à l'annulation des décisions qui en découlent.\n\nNotre méthodologie de mise en place d'un système d'évaluation comprend plusieurs étapes structurées : définition des critères d'évaluation par famille de métiers (critères quantitatifs mesurables et critères qualitatifs observables), conception des grilles d'appréciation adaptées à chaque niveau hiérarchique, élaboration du calendrier annuel d'évaluation (entretiens semestriels ou annuels), et formation des évaluateurs aux techniques d'entretien et aux biais cognitifs à éviter.\n\nLe système d'évaluation que nous concevons est directement articulé avec les autres politiques RH : les résultats de l'évaluation alimentent les décisions de promotion (en lien avec les classifications conventionnelles), les plans de formation individuels (conformément à l'obligation de développement des compétences de l'employeur), et les révisions salariales (dans le respect du principe « à travail égal, salaire égal »). Cette cohérence garantit que chaque décision RH est fondée sur des éléments factuels et traçables.\n\nOdillon déploie le système d'évaluation au sein de votre organisation, accompagne les premières campagnes pour en garantir la qualité, et met en place les outils de suivi (tableaux de bord, synthèses par service) qui permettent à la direction des ressources humaines de piloter la performance collective de manière éclairée et équitable.",
            impact: "Équité perçue et conformité aux principes d'égalité de traitement"
          },
          {
            title: "Inventaire des positions/fonctions à développer",
            content: "L'identification des postes clés à développer en priorité est un exercice stratégique qui découle directement de l'obligation de l'employeur en matière de maintien et de développement des compétences inscrite dans le Code du Travail (Loi n°022/2021). Les postes critiques sont ceux dont la vacance ou la sous-performance impacterait significativement l'activité, la compétitivité ou la conformité réglementaire de l'entreprise.\n\nNotre démarche d'inventaire repose sur une méthodologie éprouvée : analyse de la criticité de chaque poste (impact opérationnel, difficulté de remplacement, temps de formation requis), cartographie des compétences détenues vs. compétences requises, identification des risques de départ (retraite prévisible, profils sollicités par le marché, fin de contrats) et évaluation de la profondeur du vivier interne pour chaque fonction stratégique.\n\nL'inventaire débouche sur un plan de développement prioritaire qui concentre les investissements formation et les actions de succession sur les postes à plus fort enjeu. Pour chaque poste critique identifié, nous définissons un plan de succession comprenant au minimum un successeur identifié (prêt immédiatement ou à moyen terme), un programme de développement pour ce successeur, et des mesures de transfert de connaissances formalisées (documentation des processus, tutorat, binômes).\n\nOdillon actualise cet inventaire annuellement en fonction des évolutions de l'activité, des mouvements de personnel et des orientations stratégiques de l'entreprise. Cet outil de pilotage permet à la direction de sécuriser la continuité opérationnelle et de prioriser les investissements en capital humain là où ils produisent le plus de valeur.",
            impact: "Focus stratégique sur les postes à forte valeur ajoutée"
          },
          {
            title: "Évaluation des emplois (fiches de poste et pesée des postes)",
            content: "Le principe « à travail d'égale valeur, rémunération égale pour tous les travailleurs, sans discrimination d'origine, d'opinion, de sexe ou d'âge » est un pilier du Code du Travail gabonais (Loi n°022/2021). Son application concrète exige que chaque poste de l'entreprise soit décrit, évalué et classé selon des critères objectifs et mesurables, indépendamment de la personne qui l'occupe.\n\nNos consultants élaborent des fiches de poste exhaustives pour chaque fonction de l'entreprise, comprenant : l'intitulé du poste et son rattachement hiérarchique, la mission principale et les missions secondaires, les activités détaillées et les résultats attendus, les compétences requises (savoirs, savoir-faire, savoir-être), les conditions d'exercice (horaires, déplacements, contraintes physiques), et les indicateurs de performance associés. Chaque fiche est validée par le titulaire du poste et son responsable hiérarchique.\n\nLa pesée des postes est réalisée selon une méthode analytique qui évalue chaque emploi sur des critères pondérés : niveau de responsabilité, complexité des tâches, autonomie décisionnelle, compétences techniques requises, impact sur les résultats de l'entreprise, et conditions de travail. Cette cotation permet d'établir une hiérarchie des emplois objective qui sert de fondement à la classification conventionnelle et à la construction de la grille salariale, en garantissant le respect du SMIG (80 000 FCFA) et du RMM (150 000 FCFA) pour chaque catégorie.\n\nOdillon assure la cohérence entre la pesée des postes, les classifications prévues par la convention collective sectorielle applicable et la politique de rémunération de l'entreprise. Ce travail de fond constitue le socle d'une gestion des ressources humaines équitable et juridiquement sécurisée.",
            impact: "Clarté des attentes et équité dans la classification des emplois"
          }
        ]
      },
      {
        icon: "BarChart3",
        name: "Politiques des Rémunérations et Avantages Divers",
        slug: "remunerations-avantages",
        tagline: "Récompensez justement",
        description: "Politique de rémunération compétitive et attractive, conforme au SMIG gabonais et aux obligations de cotisations sociales (CNSS, CNAMGS).",
        details: [
          {
            title: "Analyse des avantages et de la rémunération globale",
            content: "Le cadre salarial gabonais repose sur deux seuils légaux distincts : le SMIG (Salaire Minimum Interprofessionnel Garanti) fixé à 80 000 FCFA par mois, inchangé depuis 2006, et le Revenu Minimum Mensuel (RMM) de 150 000 FCFA net établi par le Décret n°127/PR/MTEPS du 23 avril 2010, qui intègre le salaire de base et les indemnités obligatoires (transport, logement, etc.). Aucun salarié à temps plein au Gabon ne peut percevoir une rémunération nette inférieure au RMM.\n\nNotre analyse de la rémunération globale va bien au-delà du salaire de base. Nous examinons l'ensemble des composantes : salaire fixe, primes contractuelles et conventionnelles (ancienneté, technicité, rendement), indemnités légales (transport, logement, panier), heures supplémentaires (majorées de 15 % à 100 % selon le Code du Travail), avantages en nature (véhicule, logement, téléphone) et couverture sociale obligatoire (CNSS pour la retraite et les allocations familiales, CNAMGS pour l'assurance maladie).\n\nNous réalisons un benchmarking sectoriel en comparant votre package de rémunération avec les pratiques du marché gabonais, en nous appuyant sur les grilles des conventions collectives sectorielles applicables et sur notre connaissance des niveaux de rémunération pratiqués dans votre secteur d'activité. Cette analyse permet d'identifier les écarts de compétitivité et les leviers d'amélioration de votre attractivité employeur.\n\nOdillon produit un rapport détaillé qui quantifie le coût total de la rémunération pour l'employeur (salaire brut + cotisations patronales CNSS de 18 % + CNAMGS de 4,1 % + avantages sociaux) et formule des recommandations concrètes pour optimiser votre masse salariale tout en renforçant la satisfaction et l'engagement de vos collaborateurs.",
            impact: "Compétitivité salariale assurée et conformité au RMM garanti"
          },
          {
            title: "Analyse de l'enquête salariale",
            content: "L'enquête salariale est l'outil de référence pour positionner votre politique de rémunération par rapport au marché gabonais. Au Gabon, où les données salariales publiques sont limitées, cette analyse requiert une connaissance approfondie des pratiques sectorielles et un réseau de contacts permettant d'accéder à des informations fiables et actualisées sur les niveaux de rémunération par métier et par niveau de responsabilité.\n\nNotre méthodologie d'enquête salariale intègre le coût total employeur, seul indicateur véritablement comparable entre entreprises. Ce coût comprend : le salaire brut, les cotisations patronales CNSS (18 % du brut plafonné à 1 500 000 FCFA par mois depuis la réforme du Décret n°0487/PR/MASI du 18 décembre 2025), les cotisations patronales CNAMGS (4,1 % du brut plafonné à 2 500 000 FCFA), les avantages en nature valorisés, et les contributions volontaires de l'employeur (mutuelle complémentaire, plan d'épargne, assurance prévoyance).\n\nL'analyse est réalisée par famille de métiers, par niveau de classification conventionnelle et par zone géographique (Libreville vs. provinces). Nous comparons votre positionnement sur chaque centile de la distribution salariale (médiane, quartile supérieur, décile supérieur) pour chaque poste benchmark. Les écarts identifiés sont analysés en termes d'impact sur l'attractivité (capacité à recruter les profils recherchés) et sur la rétention (risque de départ des talents en poste).\n\nOdillon vous remet un rapport d'analyse assorti de recommandations chiffrées : ajustements salariaux prioritaires, restructuration des composantes de la rémunération, introduction ou amélioration d'avantages à fort impact perçu mais à coût maîtrisé. Chaque recommandation est budgétisée pour permettre à la direction de prendre des décisions éclairées.",
            impact: "Positionnement salarial optimal sur le marché gabonais"
          },
          {
            title: "Gestion des augmentations des salaires",
            content: "La révision salariale est un moment clé de la vie de l'entreprise qui doit concilier performance économique, équité interne et conformité légale. Le Code du Travail gabonais (Loi n°022/2021) impose le respect du principe d'égalité de rémunération : « à travail d'égale valeur, rémunération égale pour tous les travailleurs, sans discrimination d'origine, d'opinion, de sexe ou d'âge ». Toute politique d'augmentation qui ne respecterait pas ce principe expose l'employeur à des réclamations individuelles et à des actions collectives.\n\nNotre accompagnement dans la gestion des augmentations comprend la définition d'une politique de révision salariale transparente et structurée : critères d'éligibilité objectifs (ancienneté, résultats de l'évaluation, atteinte des objectifs), enveloppe budgétaire calibrée en fonction de la capacité financière de l'entreprise et de l'évolution du coût de la vie au Gabon, matrice d'augmentation croisant performance individuelle et positionnement salarial, et calendrier de mise en oeuvre.\n\nNous veillons à ce que le processus intègre les contraintes spécifiques du contexte gabonais : augmentations conventionnelles prévues par les accords de branche, revalorisations du SMIG ou du RMM décidées par les pouvoirs publics (le SMIG n'a pas été réévalué depuis 2006, mais une révision peut intervenir à tout moment), et évolution des cotisations sociales qui impacte directement le coût total des augmentations pour l'employeur.\n\nOdillon produit les simulations budgétaires qui permettent à la direction de mesurer l'impact de différents scénarios d'augmentation sur la masse salariale globale, incluant les effets induits sur les cotisations patronales CNSS et CNAMGS. Nous accompagnons également la communication des décisions aux collaborateurs pour en maximiser l'impact motivationnel.",
            impact: "Motivation maintenue et respect du principe d'égalité"
          },
          {
            title: "Assistance dans l'élaboration de la grille salariale",
            content: "La grille salariale est l'architecture de la politique de rémunération de l'entreprise. Au Gabon, elle doit impérativement respecter deux planchers légaux : le SMIG de 80 000 FCFA par mois (inchangé depuis 2006) et le Revenu Minimum Mensuel de 150 000 FCFA net (Décret n°127/PR/MTEPS du 23 avril 2010). Par ailleurs, les conventions collectives sectorielles, qui constituent le cadre conventionnel en l'absence de convention collective nationale unique au Gabon, définissent des grilles minimales par catégorie et échelon que l'employeur ne peut pas déroger à la baisse.\n\nNotre méthodologie d'élaboration de la grille salariale s'appuie sur les résultats de la pesée des postes et de l'enquête salariale. La grille est structurée en bandes salariales correspondant aux niveaux de classification conventionnelle, avec pour chaque bande un minimum, un point médian et un maximum. L'amplitude entre les niveaux reflète la progression de la complexité et de la responsabilité, tandis que la largeur de chaque bande permet de rémunérer l'ancienneté et la performance individuelle.\n\nChaque catégorie d'emploi est positionnée dans la grille en fonction de sa cotation (issue de la pesée des postes) et de la convention collective applicable. Nous intégrons les primes obligatoires et conventionnelles (ancienneté, technicité, salissure, panier, etc.) comme composantes structurelles de la rémunération, et nous vérifions que le total perçu par chaque salarié respecte le RMM de 150 000 FCFA net, tous éléments de rémunération confondus.\n\nOdillon livre une grille salariale opérationnelle, accompagnée de sa notice d'utilisation, de la matrice de positionnement des salariés actuels et d'un plan de rattrapage chiffré pour les éventuels écarts identifiés. La grille est conçue pour évoluer facilement en cas de revalorisation du SMIG, de modification des conventions collectives ou de changement de stratégie de l'entreprise.",
            impact: "Équité interne garantie et conformité aux conventions collectives"
          },
          {
            title: "Audit des avantages sociaux et autres avantages",
            content: "Le système de protection sociale gabonais repose sur deux piliers obligatoires : la CNSS (Caisse Nationale de Sécurité Sociale), qui couvre la retraite, les allocations familiales et les accidents du travail/maladies professionnelles, et la CNAMGS (Caisse Nationale d'Assurance Maladie et de Garantie Sociale), qui assure la couverture maladie universelle. Depuis la réforme du Décret n°0487/PR/MASI du 18 décembre 2025, les cotisations CNSS s'élèvent à 23 % du brut plafonné (18 % employeur, 5 % salarié) sur un plafond de 1 500 000 FCFA/mois. Les cotisations CNAMGS, régies par le Décret n°518/PR/MDSFPSSN du 22 décembre 2016, représentent 6,1 % (4,1 % employeur, 2 % salarié) sur un plafond de 2 500 000 FCFA.\n\nNotre audit examine en détail chaque composante du package social : conformité des déclarations et versements CNSS et CNAMGS, respect des droits à congés payés (24 jours ouvrables par an minimum, avec majoration d'ancienneté de 2 jours supplémentaires après 5 ans, 4 jours après 10 ans, 6 jours après 15 ans, et 8 jours après 20 ans de service), prise en charge effective des accidents du travail, et couverture des prestations familiales pour les salariés ayant des enfants à charge.\n\nAu-delà des obligations légales, nous évaluons la compétitivité de vos avantages complémentaires : indemnité de logement, indemnité de transport, primes de fin d'année, mutuelle complémentaire, assurance prévoyance, plan de retraite supplémentaire, et tout autre avantage en nature ou en espèces. Pour chaque avantage, nous analysons le rapport entre le coût pour l'employeur et la valeur perçue par le salarié.\n\nOdillon formule des recommandations d'optimisation de votre package social, en identifiant les avantages à fort impact sur l'engagement des collaborateurs et à coût maîtrisé pour l'entreprise. Nous veillons à ce que chaque avantage soit correctement valorisé sur le bulletin de paie et intégré dans les bases de calcul des cotisations sociales conformément à la réglementation en vigueur.",
            impact: "Packages attractifs et conformes aux obligations sociales gabonaises"
          }
        ]
      }
    ],
  legalReferences: [
    { title: "Code du Travail gabonais 2021", description: "Loi n°022/2021 du 19 novembre 2021 - 413 articles", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/Code-Travail-Gabon-2021.pdf", type: "pdf" },
    { title: "Code de protection sociale", description: "Loi n°28/2016 du 6 février 2017", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/Code-Protection-Sociale-Gabon-2017.pdf", type: "pdf" },
    { title: "CNSS - Réforme 2026", description: "Décret n°0487/PR/MASI du 18 décembre 2025 - Nouveaux taux de cotisations", url: "https://www.cleiss.fr/docs/cotisations/gabon.html", type: "link" },
    { title: "CNAMGS - Taux de cotisations", description: "Décret n°518/PR/MDSFPSSN du 22 décembre 2016", url: "https://www.cleiss.fr/docs/regimes/regime_gabon.html", type: "link" },
    { title: "Convention Collective Interprofessionnelle", description: "Convention encadrant les relations de travail tous secteurs au Gabon", url: "https://xqkaraihiqqfcasmduuh.supabase.co/storage/v1/object/public/legal-documents/Convention-Collective-Gabon.pdf", type: "pdf" }
  ]
  }
